### ISSUE TITLE
Specifying stdin using an expression causes filemapper error

### ISSUE THREAD

**Issue by mb1069** [common-workflow-language/cwltool#1004]
``` cwl
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

baseCommand: ['cat']

stdin: $(inputs.input_file.basename)
inputs:
  input_file:
    type: File

outputs: []
```

On macOS & Linux:

```
(base) mdb-ml:cwltool mdb$ cwltool tmp.cwl --input_file README.rst 
/Users/mdb/miniconda3/bin/cwltool 1.0.20181210073803
Resolved 'tmp.cwl' to 'file:///Users/mdb/work/cwltool/tmp.cwl'
[job tmp.cwl] /private/tmp/docker_tmpeknwy5b4$ cat < README.rst
[job tmp.cwl] Job error:
README.rst missing from pathmapper
[job tmp.cwl] completed permanentFail
{}
Final process status is permanentFail
```

**Comment by elagina** [comment]
Hello,

I was wondering if there is any update on this issue.

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

baseCommand: ['cat']

stdin: $(inputs.input_file)

inputs:
  input_file:
    type: File
    streamable: true

outputs: []
```
```
INFO [job test.cwl] /tmp/syfm9bqe$ cat < hello.txt 
ERROR [job test.cwl] Job error: hello.txt missing from pathmapper
WARNING [job test.cwl] completed permanentFail
```

Thank you!
