### ISSUE TITLE
cwltool:overrides: add an alias for any Process

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1052]
`overrides_all.yml`
```
cwltool:overrides:
  cwtooll:all:
    requirements:
      ResourceRequirement:
        ramMax: 100
```
to apply to every Process

and
`overrides_main.yml`
```
cwltool:overrides:
  cwtooll:main:
    requirements:
      ResourceRequirement:
        ramMax: 100
```
to apply to just the top level/main Process (and then the normal inheritance rules apply)

**Comment by altairwei** [comment]
Can I use an alias like this?

```yaml
cwltool:overrides:
  cwltool:main#AnnotateR2:
    requirements:
      ResourceRequirement:
        coresMin: 6
        ramMin: 79872
        outdirMin: 143360
```
