### ISSUE TITLE
Parallel execution javascript evaluation error

### ISSUE THREAD

**Issue by tonyyzy** [common-workflow-language/cwltool#1065]
## Expected Behavior
Jobs execute in parallel

## Actual Behavior
Jobs executed in parallel but an expression evaluation error caused successful workflow steps to fail. This error tends to occur when multiple steps finished together.

## Workflow Code
```
cat hisat2-6.cwl
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
requirements:
  ScatterFeatureRequirement: {}
  MultipleInputFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  InlineJavascriptRequirement: {}

inputs:
  threads: int
  genomeDir: Directory
  annotation: File
  subject_name1: string
  subject_name2: string
  subject_name3: string
  subject_name4: string
  subject_name5: string
  subject_name6: string
  fastq1: File[]
  fastq2: File[]
  fastq3: File[]
  fastq4: File[]
  fastq5: File[]
  fastq6: File[]

outputs:
  hisat2_align_out:
    type: Directory
    outputSource: hisat2_align_folder/out
steps:
  hisat2_align_1:
    run: /data/rnaseq/RNASeq/cwl-tools/docker/hisat2_align.cwl
    in:
      threads: threads
      index_directory: genomeDir
      first_pair:
        source: fastq1
        valueFrom: $(self[0])
      second_pair:
        source: fastq1
        valueFrom: $(self[1])
      sam_name:
        source: subject_name1
        valueFrom: $(self + '.sam')
    out: [sam_output, hisat2_align_out]

  hisat2_align_2:
    run: /data/rnaseq/RNASeq/cwl-tools/docker/hisat2_align.cwl
    in:
      threads: threads
      index_directory: genomeDir
      first_pair:
        source: fastq2
        valueFrom: $(self[0])
      second_pair:
        source: fastq2
        valueFrom: $(self[1])
      sam_name:
        source: subject_name2
        valueFrom: $(self + '.sam')
    out: [sam_output, hisat2_align_out]

  hisat2_align_3:
    run: /data/rnaseq/RNASeq/cwl-tools/docker/hisat2_align.cwl
    in:
      threads: threads
      index_directory: genomeDir
      first_pair:
        source: fastq3
        valueFrom: $(self[0])
      second_pair:
        source: fastq3
        valueFrom: $(self[1])
      # single_file: fastq3
      sam_name:
        source: subject_name3
        valueFrom: $(self + '.sam')
    out: [sam_output, hisat2_align_out]

  hisat2_align_4:
    run: /data/rnaseq/RNASeq/cwl-tools/docker/hisat2_align.cwl
    in:
      threads: threads
      index_directory: genomeDir
      first_pair:
        source: fastq4
        valueFrom: $(self[0])
      second_pair:
        source: fastq4
        valueFrom: $(self[1])
      # single_file: fastq4
      sam_name:
        source: subject_name4
        valueFrom: $(self + '.sam')
    out: [sam_output, hisat2_align_out]

  hisat2_align_5:
    run: /data/rnaseq/RNASeq/cwl-tools/docker/hisat2_align.cwl
    in:
      threads: threads
      index_directory: genomeDir
      first_pair:
        source: fastq5
        valueFrom: $(self[0])
      second_pair:
        source: fastq5
        valueFrom: $(self[1])
      # single_file: fastq4
      sam_name:
        source: subject_name5
        valueFrom: $(self + '.sam')
    out: [sam_output, hisat2_align_out]

  hisat2_align_6:
    run: /data/rnaseq/RNASeq/cwl-tools/docker/hisat2_align.cwl
    in:
      threads: threads
      index_directory: genomeDir
      first_pair:
        source: fastq6
        valueFrom: $(self[0])
      second_pair:
        source: fastq6
        valueFrom: $(self[1])
      # single_file: fastq4
      sam_name:
        source: subject_name6
        valueFrom: $(self + '.sam')
    out: [sam_output, hisat2_align_out]

  hisat2_align_folder:
    run: /data/rnaseq/RNASeq/cwl-tools/folder.cwl
    in:
      item:
      - hisat2_align_1/hisat2_align_out
      - hisat2_align_2/hisat2_align_out
      - hisat2_align_3/hisat2_align_out
      - hisat2_align_4/hisat2_align_out
      - hisat2_align_5/hisat2_align_out
      - hisat2_align_6/hisat2_align_out
      name:
        valueFrom: "hisat2"
    out: [out]

```

```
#!usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: 
hints:
  ShellCommandRequirement: {}
  DockerRequirement:
    dockerPull: quay.io/biocontainers/hisat2:2.1.0--py27h2d50403_2
requirements:
  InlineJavascriptRequirement: {}
arguments:
  - position: 1
    valueFrom: "mkdir"
  - position: 2
    valueFrom: $(inputs.sam_name.split('.')[0])
  - position: 3
    shellQuote: False
    valueFrom: '&& cd'
  - position: 4
    valueFrom: $(inputs.sam_name.split('.')[0])
  - position: 5
    shellQuote: False
    valueFrom: '&& hisat2'

inputs:
  input_type:
    type: string
    default: "-q"
    inputBinding:
      position: 6
  index_directory:
    type: Directory
    inputBinding:
      position: 7
      prefix: "-x"
      valueFrom: "${return inputs.index_directory.path + '/' 
                  + inputs.index_directory.listing[0].nameroot.split('.').slice(0,-1).join('.')}"
  first_pair:
    type: File?
    inputBinding:
      position: 8
      prefix: "-1"
  second_pair:
    type: File?
    inputBinding:
      position: 9
      prefix: "-2"
  single_file:
    type: File[]?
    inputBinding:
      position: 10
      prefix: -U
  sra_acc:
    type: string?
    inputBinding:
      position: 11
      prefix: --sra-acc
  sam_name:
    type: string
    inputBinding:
      position: 12
      prefix: -S
  threads:
    type: int
    inputBinding:
      position: 13
      prefix: -p
  XSTag:
    type: string?
    default: --dta-cufflinks
    inputBinding:
      position: 14
  log:
    type: string
    default: "log.txt"
    inputBinding:
      position: 15
      prefix: --summary-file

outputs:
  hisat2_align_out:
    type: Directory
    outputBinding:
      glob: $(inputs.sam_name.split('.')[0])
  
  sam_output:
    type: File
    outputBinding:
      glob: $(inputs.sam_name.split('.')[0] + '/' + inputs.sam_name)
```
### Full traceback too long for issue, a txt log file is attacked below
[log-6.txt](https://github.com/common-workflow-language/cwltool/files/2885415/log-6.txt)

```pytb


```

## Your Environment
* cwltool version: 1.0.20180820141117

**Comment by kkarolis** [comment]
Hey, @tonyyzy, 

Thanks for posting such a thorough report. Excuse me if its unreasonable to ask, but would it be possible for you to attach `hisat2_align.cwl` and `folder.cwl` files as well ?

**Comment by tonyyzy** [comment]
Hi @kkarolis 

`hisat2_align.cwl` was attached below the workflow part. I've made the title bold so it's clearer. I also included a txt version as attachments.
[hisat2_align.cwl.txt](https://github.com/common-workflow-language/cwltool/files/2898122/hisat2_align.cwl.txt)
[folder.cwl.txt](https://github.com/common-workflow-language/cwltool/files/2898123/folder.cwl.txt)

**Comment by tonyyzy** [comment]
@kkarolis , Sorry this is the minimal example I could create...I can provide the input yml files and point you to the test data if that helps.
I understand that parallel is suppose to be an experimental feature for `cwltool` and `toil` might be more suitable for this purpose. However, for a single node system, I found the `toil`'s parallel execution a bit overkill (and `toil` might face the same javascript problem, but I can't recreate the issue everytime). So yeah, I think `cwltool`'s parallel feature is really useful for a single node, high core count system.

**Comment by kkarolis** [comment]
Totally missed the algo file, doh! 

re: the inputs,  if it's not a huge problem for you that would surely help!

It seems like a race condition on nodejs standard output stream handling, i'm looking into it, but will have to learn the codebase so this will take a bit.

By the way, have you tried to rerun the same thing on newest version of cwltool ?

**Comment by mr-c** [comment]
Partial input object using public data:

```
threads: 12
subject_name1: SRR3584106
subject_name2: SRR3584107
subject_name3: SRR3584108
subject_name4: SRR3584109
subject_name5: SRR3584110
subject_name6: SRR3584111
annotation:
  class: File
  location: http://ftp.ensemblgenomes.org/pub/protists/release-42/gff3/protists_alveolata1_collection/plasmodium_yoelii_gca_900002395/Plasmodium_yoelii_gca_900002395.PYYM01.42.gff3.gz  # ?
fastq1:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/006/SRR3584106/SRR3584106_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/006/SRR3584106/SRR3584106_2.fastq.gz
fastq2:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/007/SRR3584107/SRR3584107_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/007/SRR3584107/SRR3584107_2.fastq.gz
fastq2:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/008/SRR3584108/SRR3584108_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/008/SRR3584108/SRR3584108_2.fastq.gz
fastq3:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/008/SRR3584108/SRR3584108_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/008/SRR3584108/SRR3584108_2.fastq.gz
fastq4:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/009/SRR3584109/SRR3584109_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/009/SRR3584109/SRR3584109_2.fastq.gz
fastq5:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/000/SRR3584110/SRR3584110_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/000/SRR3584110/SRR3584110_2.fastq.gz
fastq6:
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/001/SRR3584111/SRR3584111_1.fastq.gz
- class: File
  location: http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR358/001/SRR3584111/SRR3584111_2.fastq.gz
```

**Comment by tonyyzy** [comment]
Michael, thanks for providing a partial input file!

@kkarolis , it takes a few steps to recreate the necessary test files, Plasmodium has a really small genome so hopefully it doesn't take long.

**Download the genome file:**
```
ftp://ftp.ensemblgenomes.org/pub/protists/release-42/fasta/protists_alveolata1_collection/plasmodium_yoelii_gca_900002395/dna/Plasmodium_yoelii_gca_900002395.PYYM01.dna.toplevel.fa.gz
```

Hisat2 doesn't gzip genome and gtf for the indexing step, so you would need to unzip the above two files.

**hisat2 indexing**
Run this cwl script to create the index
Note, specify `--outdir` so the indexes would be in a subdirectory
e.g. `cwl-runner --outdir=./HISAT2Index ./hisat2_build.cwl ./hisat2_build.yml`

*hisat2_build.cwl*
```
#!usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: hisat2-build
hints:
   DockerRequirement:
      dockerPull: quay.io/biocontainers/hisat2:2.1.0--py27h2d50403_2
stdout: log.txt
inputs:
   reference:
      type: File
      inputBinding:
         position: 1
         prefix: -f
   basename:
      type: string
      inputBinding:
         position: 2
   threads:
      type: int
      inputBinding:
         prefix: -p

outputs:
   ht:
      type: File[]
      outputBinding:
         glob: "*"
   log:
      type: stdout
```
*hisat2_build.yml*
```
threads: 2
reference:
  class: File
  path: /data/rnaseq/GenomeIndex/Plasmodium_Yoelii/Plasmodium_yoelii_gca_900002395.PYYM01.dna.toplevel.fa
basename: "P.yoelii"
```

**input yml for the workflow**
You can follow Michael's input for downloading files at runtime, but I'm not sure if this error still pop up if the finish times for steps are more separated.
In case you need to download the 12 fastq files, they can be found here, [https://www.ebi.ac.uk/ena/data/view/PRJNA322665](https://www.ebi.ac.uk/ena/data/view/PRJNA322665)
The top six entries are what you need and two fastq each.

*workflow.yml*
replace the path of `genomeDir` to the path of the directory where the indexes are stored in the previous step.
replace the path to `annotation` to the path of the annotation file which can be downloaded here: 
[ftp://ftp.ensemblgenomes.org/pub/protists/release-42/gtf/protists_alveolata1_collection/plasmodium_yoelii_gca_900002395/Plasmodium_yoelii_gca_900002395.PYYM01.42.gtf.gz](ftp://ftp.ensemblgenomes.org/pub/protists/release-42/gtf/protists_alveolata1_collection/plasmodium_yoelii_gca_900002395/Plasmodium_yoelii_gca_900002395.PYYM01.42.gtf.gz)
```
threads: 12
genomeDir:
  class: Directory
  path: /data/rnaseq/GenomeIndex/Plasmodium_Yoelii/HISAT2Index
annotation:
  class: File
  path: /data/rnaseq/GenomeIndex/Plasmodium_Yoelii/Plasmodium_yoelii_gca_900002395.PYYM01.42.gtf
subject_name1: SRR3584106
subject_name2: SRR3584107
subject_name3: SRR3584108
subject_name4: SRR3584109
subject_name5: SRR3584110
subject_name6: SRR3584111
fastq1:
  - {class: File, path: /data/rnaseq/test/plas/SRR3584106_1.fastq.gz}
  - {class: File, path: /data/rnaseq/test/plas/SRR3584106_2.fastq.gz}
fastq2:
  - {class: File, path: /data/rnaseq/test/plas/SRR3584107_1.fastq.gz}
  - {class: File, path: /data/rnaseq/test/plas/SRR3584107_2.fastq.gz}
fastq3:
  - {class: File, path: /data/rnaseq/test/plas/SRR3584108_1.fastq.gz}
  - {class: File, path: /data/rnaseq/test/plas/SRR3584108_2.fastq.gz}
fastq4:
  - {class: File, path: /data/rnaseq/test/plas/SRR3584109_1.fastq.gz}
  - {class: File, path: /data/rnaseq/test/plas/SRR3584109_2.fastq.gz}
fastq5:
  - {class: File, path: /data/rnaseq/test/plas/SRR3584110_1.fastq.gz}
  - {class: File, path: /data/rnaseq/test/plas/SRR3584110_2.fastq.gz}
fastq6:
  - {class: File, path: /data/rnaseq/test/plas/SRR3584111_1.fastq.gz}
  - {class: File, path: /data/rnaseq/test/plas/SRR3584111_2.fastq.gz}
```
