### ISSUE TITLE
Odd validation failures for valid document

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/cwltool#1096]
## Expected Behavior
Tool should pass validation.

## Actual Behavior
Tool fails validation.

## Workflow Code
```
class: CommandLineTool
cwlVersion: v1.0
doc: ''
inputs:
  input:
    type: string[]
    inputBinding:
      prefix: --dak
      position: 0

outputs: []
baseCommand: 'echo'
hints: []
# requirements: []

```

## Full Traceback
```pytb
I'm sorry, I couldn't load this CWL file.
The error was:
Traceback (most recent call last):
  File "/.../cwltool/lib/python3.7/site-packages/cwltool/main.py", line 658, in main
    skip_schemas=args.skip_schemas)
  File "/.../cwltool/lib/python3.7/site-packages/cwltool/load_tool.py", line 308, in resolve_and_validate_document
    processobj, document_loader, fileuri, loadingContext.enable_dev, metadata)))
  File "/.../cwltool/lib/python3.7/site-packages/schema_salad/sourceline.py", line 187, in cmap
    d[k] = cmap(v, lc=d.lc.data[k], fn=fn)
  File "/.../cwltool/lib/python3.7/site-packages/schema_salad/sourceline.py", line 194, in cmap
    if k in d.lc.data:
TypeError: argument of type 'NoneType' is not iterable```

## Your Environment
`cwltool 1.0.20190228155703`
