### ISSUE TITLE
CWLtool asks for InlineJavascriptRequirement for parameter reference

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/cwltool#1097]
## Expected Behavior
Parameter references should work without specifying `InlineJavascriptRequirement`

## Actual Behavior
CWLtool asks for `InlineJavascriptRequirement` for parameter reference

## Workflow Code
```
class: CommandLineTool
cwlVersion: v1.0
doc: ''
inputs: []
outputs: []
baseCommand: 'echo'
arguments:
  - prefix: --output
    valueFrom: $(2 + 4).ext
```

## Full Traceback
```pytb
cmd.line.binding.cwl:9:5: Expression evaluation error:
                          Syntax error in parameter reference '(2 + 4)'. This could be due to using
                          Javascript code without specifying InlineJavascriptRequirement.
```

## Your Environment
`cwltool 1.0.20190228155703`
