### ISSUE TITLE
cwl failed to locate the output file if it has '+' in its name

### ISSUE THREAD

**Issue by byb121** [common-workflow-language/cwltool#1098]
## Expected Behavior
copy and rename an input file

## Actual Behavior
cwltool failed to locate the output

## Workflow Code
```
#!/usr/bin/env cwl-runner

class: CommandLineTool

cwlVersion: v1.0

requirements:
  InitialWorkDirRequirement:
    listing:
      - entry: $(inputs.srcfile)

inputs:
  srcfile:
    type: File
    inputBinding:
      position: 1
      shellQuote: true
  newname:
    type: string
    inputBinding:
      position: 2
      shellQuote: true
outputs:
  outfile:
    type: File
    outputBinding:
      glob: $(inputs.newname)

baseCommand: ["cp"]
```

## Full Traceback
```pytb
/usr/local/bin/cwltool 1.0.20181217162649
Resolved 'cp.cwl' to 'file:///home/yaobo/Downloads/cp.cwl'
[job cp.cwl] initializing from file:///home/yaobo/Downloads/cp.cwl
[job cp.cwl] {
    "srcfile": {
        "class": "File",
        "location": "file:///home/yaobo/Downloads/colo-829-bl+12_i.fq.gz",
        "size": 0,
        "basename": "colo-829-bl+12_i.fq.gz",
        "nameroot": "colo-829-bl+12_i.fq",
        "nameext": ".gz"
    },
    "newname": "colo-829-bl_i+.fastq.gz"
}
[job cp.cwl] path mappings is {
    "file:///home/yaobo/Downloads/colo-829-bl+12_i.fq.gz": [
        "/home/yaobo/Downloads/colo-829-bl+12_i.fq.gz",
        "/tmp/f2d53v_6/colo-829-bl+12_i.fq.gz",
        "File",
        false
    ]
}
[job cp.cwl] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "cp"
    },
    {
        "position": [
            1,
            "srcfile"
        ],
        "shellQuote": true,
        "datum": {
            "class": "File",
            "location": "file:///home/yaobo/Downloads/colo-829-bl+12_i.fq.gz",
            "size": 0,
            "basename": "colo-829-bl+12_i.fq.gz",
            "nameroot": "colo-829-bl+12_i.fq",
            "nameext": ".gz",
            "path": "/tmp/f2d53v_6/colo-829-bl+12_i.fq.gz",
            "dirname": "/tmp/f2d53v_6"
        }
    },
    {
        "position": [
            2,
            "newname"
        ],
        "shellQuote": true,
        "datum": "colo-829-bl_i+.fastq.gz"
    }
]
[job cp.cwl] initial work dir {
    "file:///home/yaobo/Downloads/colo-829-bl+12_i.fq.gz": [
        "/home/yaobo/Downloads/colo-829-bl+12_i.fq.gz",
        "/tmp/f2d53v_6/colo-829-bl+12_i.fq.gz",
        "File",
        true
    ]
}
[job cp.cwl] /tmp/f2d53v_6$ cp \
    /tmp/f2d53v_6/colo-829-bl+12_i.fq.gz \
    colo-829-bl_i+.fastq.gz
Could not collect memory usage, job ended before monitoring began.
[job cp.cwl] Job error:
Error collecting output for parameter 'outfile':
cp.cwl:24:3: Traceback (most recent call last):
cp.cwl:24:3: 
cp.cwl:24:3:   File "/usr/local/lib/python3.6/dist-packages/cwltool/command_line_tool.py", line 612, in collect_output_ports
cp.cwl:24:3:     compute_checksum=compute_checksum)
cp.cwl:24:3: 
cp.cwl:24:3:   File "/usr/local/lib/python3.6/dist-packages/cwltool/command_line_tool.py", line 702, in collect_output
cp.cwl:24:3:     with fs_access.open(rfile["location"], "rb") as f:
cp.cwl:24:3: 
cp.cwl:24:3:   File "/usr/local/lib/python3.6/dist-packages/cwltool/stdfsaccess.py", line 41, in open
cp.cwl:24:3:     return open(self._abs(fn), mode)
cp.cwl:24:3: 
cp.cwl:24:3: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/f2d53v_6/colo-829-bl_i%2B.fastq.gz'
[job cp.cwl] completed permanentFail
[job cp.cwl] {}
[job cp.cwl] Removing input staging directory /tmp/tmpb80kmu_k
[job cp.cwl] Removing temporary directory /tmp/tmpidw7qb94
{}
Final process status is permanentFail
```

## Your Environment
* cwltool version: 
1.0.20181217162649
