### ISSUE TITLE
Argument with prefix = empty string and separate = false is omitted from cmd line

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/cwltool#1165]
## Expected Behavior
Argument with `prefix: ""` and `separate: false` should be in the command line

## Actual Behavior
Argument is not in the command line

## Workflow Code
```
class: CommandLineTool
cwlVersion: v1.0
baseCommand: []
inputs:
  echo: boolean
outputs: []
arguments:
- position: 1
  shellQuote: false
  prefix: ''
  valueFrom: "non_existing_app"
- position: 0
  prefix: ''
  separate: false
  shellQuote: false
  valueFrom: "echo"
requirements:
- class: ShellCommandRequirement
```

## Your Environment
* cwltool version: 1.0.20190621234233
works fine with cwltool version: 1.0.20190228155703
