### ISSUE TITLE
id in CommandLineTool causes dot graph to not be printed correctly

### ISSUE THREAD

**Issue by itajaja** [common-workflow-language/cwltool#1204]
`cwltool --print-dot workflow.cwl` produces an empty output if `CommandLineTool` has an `id` field. I was not able to identify a further root cause, but If the `id` field is removed, than `--print-dot` works correctly as expected.

## Expected Behavior
```
digraph {compound=true
"workflow_with_id.cwl#my_step" [label="my_step"]
}%
```

this is the expected graph. This is what gets correctly printed if I remove the `id` root field from the my_step.cwl file

## Actual Behavior
```
digraph {compound=true
}%
```

## Workflow Code
workflow:

```yml
class: Workflow
cwlVersion: v1.0
requirements:
- class: StepInputExpressionRequirement
- class: InlineJavascriptRequirement
- class: MultipleInputFeatureRequirement

inputs:
  foo: string

outputs:
  bar:
    type: string
    outputSource: my_step/bar

steps:
  my_step:
    run: ./my_step.cwl
    in:
      foo:
        source: foo
    out: [bar]
```

step:

```yml
class: CommandLineTool
cwlVersion: v1.0
id: my_step
baseCommand:
  - echo
inputs:
  foo: string
outputs:
  bar:
    type: string

```

## Your Environment
`1.0.20190915164430`

**Comment by itajaja** [comment]
cc @meyermj

**Comment by itajaja** [comment]
if I do `--print-rdf` the two files look exactly the same except for the following line:

```
<file:///Users/gtagliabue/workspace/qsi/consular/tests/test_data/workflow_samples/miniasm.cwl#my_step> a cwl:CommandLineTool ;
```

vs

```
<file:///Users/gtagliabue/workspace/qsi/consular/tests/test_data/workflow_samples/miniasm.cwl> a cwl:CommandLineTool ;
```

and the fact that the order for the workflow and steps file is inverted

**Comment by itajaja** [comment]
ping 👋

**Comment by mr-c** [comment]
Perhaps we should be stripping these `id`s out, as they then don't match the generated IDs for the other components


```
ipdb> print(ruamel.yaml.round_trip_dump(wf.steps[0].embedded_tool.tool))                                                                                                                                    
class: CommandLineTool
id: file:///home/michael/cwltool/1204-step.cwl#my_step
baseCommand:
- echo
inputs:
- type: string
  id: file:///home/michael/cwltool/1204-step.cwl#foo
outputs:
- type: string

  id: file:///home/michael/cwltool/1204-step.cwl#bar
name: file:///home/michael/cwltool/1204-step.cwl
hints:
- class: LoadListingRequirement
  loadListing: deep_listing
- class: NetworkAccess
  networkAccess: true
cwlVersion: v1.1
http://commonwl.org/cwltool#original_cwlVersion: v1.0
```

Here's a quick fix, but a better fix might be in schema-salad; what do you think @tetron ?

``` diff
commit 607b3ff04d3632420aff1899d57a37c3d7acefdc (HEAD -> reset_manual_id)
Author: Michael R. Crusoe <michael.crusoe@gmail.com>
Date:   Tue Oct 15 11:13:02 2019 +0200

    overwrite manually set ids

diff --git a/cwltool/load_tool.py b/cwltool/load_tool.py
index c651c041..2d97b769 100644
--- a/cwltool/load_tool.py
+++ b/cwltool/load_tool.py
@@ -112,6 +112,8 @@ def fetch_document(argsworkflow,        # type: Union[Text, Dict[Text, Any]]
                                         resolver=loadingContext.resolver,
                                         document_loader=loadingContext.loader)
         workflowobj = loadingContext.loader.fetch(fileuri)
+        if 'name' in workflowobj:
+            workflowobj['id'] = workflowobj['name']
         return loadingContext, workflowobj, uri
     if isinstance(argsworkflow, dict):
         uri = argsworkflow["id"] if argsworkflow.get("id") else "_:" + Text(uuid.uuid4())
```
