### ISSUE TITLE
Output evaluation is not including secondary files.

### ISSUE THREAD

**Issue by illusional** [common-workflow-language/cwltool#1229]
##  Expected Behavior

> I'm trying to rewrite the extension of a secondary file.

The `outputEval` block does not contain an array for secondaryFiles.

## Actual Behavior

Within `self` in the `outputEval` javascript block, no `secondaryFiles` property is found.

This is because the ["outputEval" block is before](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/command_line_tool.py#L779-L781) the [secondaryFiles resolution block](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/command_line_tool.py#L795-L828). Traceback below shows the missing block.

## Workflow Code

cwl
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: "ls"
inputs:
  bam:
    type: File
    secondaryFiles: ["^.bai"]
outputs:
  std: stdout
  out:
    type: File
    secondaryFiles: ["^.bai"]
    outputBinding:
      glob: $(inputs.bam.basename)
      outputEval: |
        ${
            console.log(self)
            self[0].secondaryFiles[0].basename=".bai"
        }
requirements:
  InitialWorkDirRequirement:
    listing:
      - $(inputs.bam)
  InlineJavascriptRequirement: {}
```

## Full Traceback

_This has been formatted for readability_:

```
('Error collecting output for parameter \'out\':Expression evaluation error:Expecting value: line 1 column 1 (char 0)script was:
01 "use strict";
02 var inputs = {
03     "bam": {
04         "class": "File",
05         "location": "file:///path/to/BRCA1.bam",
06         "size": 2997846,
07         "basename": "BRCA1.bam",
08         "nameroot": "BRCA1",
09         "nameext": ".bam",
10         "secondaryFiles": [
11             {
12                 "location": "file:///path/to/BRCA1.bai",
13                 "basename": "BRCA1.bai",
14                 "class": "File",
15                 "nameroot": "BRCA1",
16                 "nameext": ".bai",
17                 "path": "/private/tmp/docker_tmplo7vt97z/BRCA1.bai",
18                 "dirname": "/private/tmp/docker_tmplo7vt97z"
19             }
20         ],
21         "path": "/private/tmp/docker_tmplo7vt97z/BRCA1.bam",
22         "dirname": "/private/tmp/docker_tmplo7vt97z"
23     }
24 };
25 var self = [
26     {
27         "location": "file:///private/tmp/docker_tmplo7vt97z/BRCA1.bam",
28         "path": "/private/tmp/docker_tmplo7vt97z/BRCA1.bam",
29         "basename": "BRCA1.bam",
30         "nameroot": "BRCA1",
31         "nameext": ".bam",
32         "class": "File",
33         "checksum": "sha1$8a38a4e8d58c91d9aaca8cdc739e05eddf7dec1d",
              # missing secondaryFiles here
34         "size": 2997846
35     }
36 ];
37 var runtime = {
38     "cores": 1,
39     "ram": 1024,
40     "tmpdirSize": 1024,
41     "outdirSize": 1024,
42     "tmpdir": "/private/var/folders/jz/y9gqxt_s7jxcjkc26gr71ywr7zs5yz/T/tmpoer80xbz",
43     "outdir": "/private/tmp/docker_tmplo7vt97z"
44 };
45 (function(){
46     console.log(self)
47     self[0].secondaryFiles[0].basename=".bai"
48     return self
49 })()
```

## Your Environment
* cwltool version: `cwltool-1.0.20191213153910`
