### ISSUE TITLE
cwl-runner parses nested arrays repetively

### ISSUE THREAD

**Issue by lijiayong** [common-workflow-language/cwltool#124]
_nested-array.cwl_

```
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: echo
inputs:
  - id: letters
    type:
      type: array
      items:
        type: array
        items: string
    inputBinding:
      position: 1
outputs: []
```

_nested-array-job.yml_
`letters: [[a]]`

cwl-runner echos 'a' twice:

```
$ cwl-runner nested-array.cwl nested-array-job.yml 
/home/jiayong/miniconda2/bin/cwl-runner 1.0.20160708190014
[job nested-array.cwl] /tmp/tmpOqjIQT$ echo \
    a \
    a
a a
Final process status is success
{}
```
