### ISSUE TITLE
cwltool mishandles line continuations in bash scripts

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/cwltool#1271]
```
cwltool --version
/Users/kghose/.venvs/toil/bin/cwltool 3.0.20200324120055
```

The following bash script is valid

```
set -xv

echo \
  "A new line" \
  "Another line" \
  "Boo"
```

The following CWL with an embedded bash script is not correctly handled by `cwltool`.  It looks like the line continuation `\` symbol is removed?

```
class: CommandLineTool
cwlVersion: v1.0
requirements:
  DockerRequirement:
    dockerPull: sevenbridges/svsim:1.0
  InitialWorkDirRequirement:
    listing:
      - entryname: script.sh
        entry: |          
          set -xv

          echo \
            "A new line" \
            "Another line" \
            "$(inputs.foo)"

baseCommand: ["bash", "script.sh"]

inputs:
  foo: string

outputs:
  out: stdout

stdout: out.txt
```

As a contrast the SB platform executor executes this correctly.
