### ISSUE TITLE
make-template for inputs omits the format tag

### ISSUE THREAD

**Issue by alexiswl** [common-workflow-language/cwltool#1274]
## Expected Behavior
Given the cwl definition as an example
```
https://github.com/common-workflow-library/bio-cwl-tools/bwa/BWA-Index.cwl
```

Which has the inputs:
```
inputs:
  InputFile:
    type: File
    format: http://edamontology.org/format_1929 # FASTA
    inputBinding:
      position: 200
    
  IndexName:
    type: string
    inputBinding:
      prefix: "-p"
      valueFrom: $(self + ".bwt")
```

When I run:

```
cwltool --make-template ./bwa/BWA-Index.cwl
```

I would get:
```
InputFile:  # type "File"
    class: File
    format: http://edamontology.org/format_1929
    path: a/file/path
IndexName: a_string  # type "string"
```

## Actual Behavior
format for InputFile is missing.
```
InputFile:  # type "File"
    class: File
    path: a/file/path
IndexName: a_string  # type "string"
```

## Workflow Code
```
git clone https://github.com/common-workflow-library/bio-cwl-tools
cwltool --make-template ./bwa/BWA-Index.cwl
```

## Your Environment
* cwltool version: 3.0.20200324120055
