### ISSUE TITLE
Single element for an array input

### ISSUE THREAD

**Issue by jjkoehorst** [common-workflow-language/cwltool#1286]
## Expected Behavior
When providing a single directory to a cwl step which expects a list of directories it should still function when this list is a single element.

Thus when in the workflow providing the following it should work

```
  irods_upload_folders:
    run: ../irods/irods_upload.cwl
    in:
      folders: [fastqc/upload]
      destination: destination
      push: 
        default: true
    out: []
```

## Actual Behavior

However it gives the following error:

```
ERROR Tool definition failed validation:

cwls/workflows/workflow_assembly_illumina_paired.cwl:49:10: Source 'upload' of type "Directory" is
                                                            incompatible
cwls/workflows/workflow_assembly_illumina_paired.cwl:77:7:     with sink 'folders' of type
                                                              ["null", {"type": "array", "items":
                                                              "Directory"}]
```

When providing the element twice so it creates an array it works.

```
  irods_upload_folders:
    run: ../irods/irods_upload.cwl
    in:
      folders: [fastqc/upload, fastqc/upload]
      destination: destination
      push: 
        default: true
    out: []
```

## Workflow Code
```
See above
```

## Your Environment
* cwltool version:  3.0.20200416192244
Check using ``cwltool --version``
