### ISSUE TITLE
Workflows with v1.0 tag produce error with tools with v1.1 tag.

### ISSUE THREAD

**Issue by medcelerate** [common-workflow-language/cwltool#1291]
## Expected Behavior
Cwl tool validates with some warnings about inputs.

## Actual Behavior
Workflows written in v1.0 produce an error indicating a specification is not found in tools wrapped with v1.1

## Workflow Code
```
Workflow

#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow
label: Symphony post-processing workflow.

requirements:
  InlineJavascriptRequirement: {}
  MultipleInputFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  SubworkflowFeatureRequirement: {}

inputs:
  ForwardReads: File
  ReverseReads: File
  Reference: File
  MaxThreads: int
  SampleID: string
  KnownSiteVCF: File
  AnnotationDB: Directory

Tool

cwlVersion: v1.1
class: CommandLineTool

$namespaces:
  arv: "http://arvados.org/cwl#"
  cwltool: "http://commonwl.org/cwltool#"

hints:
  arv:APIRequirement: {}

requirements:
  DockerRequirement:
    dockerPull: "broadinstitute/gatk:4.1.7.0"
  InlineJavascriptRequirement: {}
  NetworkAccess:
    networkAccess: true
  ResourceRequirement:
    ramMin: 40000  # [MB]
    coresMin: 4        # [cores]
    tmpdirMin: 10000   # [MB]


```

## Full Traceback
```pytb
ERROR Tool definition failed validation:
../Tools/GATK/GATK-GenomicsDBImport.cwl:2:1:  Field `cwlVersion` contains undefined reference to
                                             `file:///Users/djevanclark/Documents/Sinai/covid/biocwl/Tools/GATK/v1.1
```

## Your Environment
* cwltool version: 3.0.20200324120055
