### ISSUE TITLE
cwltool inserts spurious escaping in strings

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/cwltool#1297]
`cwltool 3.0.20200324120055`

The following CWL should produce a file with the contents:
```
quote "Hello"
```
instead it returns
```
quote \"Hello\"
```

Apparently the following JS `${return 'quote "' + inputs.quote + '"'}` returns a string with escape sequence + quotes inside it, rather than just quotes.

```
#!/usr/bin/env cwl-runner

class: CommandLineTool
cwlVersion: v1.0
label: Does cwltool have a JS quoting bug?

requirements:
  InitialWorkDirRequirement:
    listing:
    - entryname: file.txt
      entry: |
        ${return 'quote "' + inputs.quote + '"'}
    - entryname: script.sh
      entry: |
        set -xe
        cat file.txt
  InlineJavascriptRequirement: {}
  ResourceRequirement:
    coresMin: 2
    ramMin: 1000

inputs:
  quote:
    type: string?

outputs:
  out:
    type: File
    outputBinding:
      glob: file.txt

baseCommand:
- echo
arguments: []
```
