### ISSUE TITLE
New cwltool error on basic gzip job

### ISSUE THREAD

**Issue by lijiayong** [common-workflow-language/cwltool#130]
_gzip.cwl_
```
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: [gzip, -f]
inputs:
  - id: input_file
    type: File
    inputBinding:
      position: 1
outputs:
  - id: gzipped_file
    type: File
    outputBinding:
      glob: "*.gz"
```
_gzip-job.yml_
```
input_file:
  class: File
  path: foo.txt
```
"Did not find output" error:
```
$ cwltool gzip.cwl gzip-job.yml 
/home/jiayong2/miniconda2/bin/cwltool 1.0.20160714182449
[job gzip.cwl] /tmp/tmptj_yvK$ gzip \
    -f \
    /tmp/tmpSu82rH/stga02c04cd-1755-4ee1-a3f8-fd830fd1d62a/foo.txt
Error while running job: Error collecting output for parameter 'gzipped_file': Did not find output file with glob pattern: '['*.gz']'
[job gzip.cwl] completed permanentFail
Final process status is permanentFail
Workflow error, try again with --debug for more information:
  Process status is ['permanentFail']
```
But it works on an earlier version
```
$ cwltool gzip.cwl gzip-job.yml 
/home/jiayong/miniconda2/bin/cwltool 1.0.20160427142240
[job 140300885704848] /home/jiayong/cwl/test/gzip$ gzip /home/jiayong/cwl/test/gzip/foo.txt
Final process status is success
{
    "gzipped_file": {
        "size": 33, 
        "path": "/home/jiayong/cwl/test/gzip/foo.txt.gz", 
        "checksum": "sha1$51fd16e775a790abd6174fd6d111300248c99761", 
        "class": "File" 
    }
}
```
