### ISSUE TITLE
runtime checking that Workflow & ExpressionTool return correct format

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwltool#1326]
## Expected Behavior
When a workflow or expression tool declares a file formats for its output parameters, they should be checked to ensure they are consistent before going to the next step.

## Actual Behavior
It doesn't check it, leading to downstream format checking errors instead, which are further away from the actual error and harder to debug.

## Workflow Code
```
cwlVersion: v1.0
class: ExpressionTool
inputs:
  inp: File  # no format set
outputs:
  # static checker now thinks it has a format, but it wasn't actually set in the Javascript,
  # so it will fail later on when the format does get checked.
  out: 
    type: File
    format: example_format
expression: |
  ${ return {out: inputs.inp}; }
```

## Your Environment

cwltool 3.0.20200720165847
