### ISSUE TITLE
Cannot specify temp directory on command line

### ISSUE THREAD

**Issue by amkibriya** [common-workflow-language/cwltool#1373]
## Expected Behavior
The cwltool stages the input files in the tmp directory specified with the `--tmpdir-prefix` and/or `--tmp-outdir-prefix` options. The specified tmp directory is also available inside the CWL script with the `$(runtime.tmpdir)` 

## Actual Behavior
If the class is `class: CommandLineTool` with NO `DockerRequirement` the files are still staged in the default `/tmp` 

## Workflow Code
```
class: CommandLineTool
cwlVersion: v1.0

$namespaces:
  edam: 'http://edamontology.org/'
  iana: 'https://www.iana.org/assignments/media-types/'
  s: 'http://schema.org/'

baseCommand: /home/radleyrp/Documents/pipelines/borg_standalone/tools/individual/interproscan/interproscan-5.36-75.0/interproscan.sh

inputs:
  - id: inputFile
    type: File
    format: edam:format_1929
    inputBinding:
      position: 8
      prefix: '--input'
    label: Input file path
    doc: >-
      Optional, path to fasta file that should be loaded on Master startup.
      Alternatively, in CONVERT mode, the InterProScan 5 XML file to convert.
  - id: applications
    type: string[]?
    inputBinding:
      position: 9
      itemSeparator: ','
      prefix: '--applications'
    label: Analysis
    doc: >-
      Optional, comma separated list of analyses. If this option is not set, ALL
      analyses will be run.
  - id: outputFormat
    type: string[]
    inputBinding:
      position: 10
      itemSeparator: ','
      prefix: '--formats'
    label: output format
    doc: >-
      Optional, case-insensitive, comma separated list of output formats.
      Supported formats are TSV, XML, JSON, GFF3, HTML and SVG. Default for
      protein sequences are TSV, XML and GFF3, or for nucleotide sequences GFF3
      and XML.
  - id: databases
    type: string? #Directory?
  - id: disableResidueAnnotation
    type: boolean?
    inputBinding:
      position: 11
      prefix: '--disable-residue-annot'
    label: Disables residue annotation
    doc: 'Optional, excludes sites from the XML, JSON output.'
  - id: seqtype
    type:
      - 'null'
      - type: enum
        symbols:
          - p
          - n
        name: seqtype
    inputBinding:
      position: 12
      prefix: '--seqtype'
    label: Sequence type
    doc: >-
      Optional, the type of the input sequences (dna/rna (n) or protein (p)).
      The default sequence type is protein.

outputs:
  - id: i5Annotations
    format: edam:format_3475
    type: File
    outputBinding:
      glob: $(inputs.inputFile.nameroot).f*.tsv

arguments:
  - position: 0
    valueFrom: '--disable-precalc'
  - position: 1
    valueFrom: '--goterms'
  - position: 2
    valueFrom: '--pathways'
  - position: 3
    prefix: '--tempdir'
    valueFrom: $(runtime.tmpdir)
requirements:
  - class: ShellCommandRequirement
  - class: ResourceRequirement
    ramMin: 15000
    coresMin: 4
  - class: InlineJavascriptRequirement
  - class: ScatterFeatureRequirement

```

## Full Traceback

The `--input` file and the specified `--temp-dir` (specified with the `$(runtime.tmpdir)`, in CWL above) are still in the default `/tmp/` in the following.

```
$ cwltool --tmpdir-prefix /mytmp1  --tmp-outdir-prefix /mytmp2  ./InterProScan-v5-none_docker-2.cwl ./InterProScan-v5_BORG-2.yml 
INFO /usr/local/bin/cwltool 3.0.20200807132242
INFO Resolved './InterProScan-v5-none_docker-2.cwl' to 'file:///.../InterProScan-v5-none_docker-2.cwl'
INFO [job InterProScan-v5-none_docker-2.cwl] /tmp/chaqb372$ /bin/sh \
    -c \
    '/home/radleyrp/Documents/pipelines/borg_standalone/tools/individual/interproscan/interproscan-5.36-75.0/interproscan.sh' '--disable-precalc' '--goterms' '--pathways' '--tempdir' '/tmp/tmp84nwbvb1' '--input' '/tmp/tmpk_rx_n6i/stg94d14706-ecc7-458a-823d-c62f20e79211/RMG_41.fa' '--applications' 'PfamA,TIGRFAM,PRINTS,PrositePatterns,Gene3d' '--formats' 'TSV'
```

## Your Environment
- cwltool version: cwltool 3.0.20200807132242
- OS: reproduced on Ubuntu 16.04 and Ubuntu 18.04 64-bit
