### ISSUE TITLE
Error when building subgraph with --target

### ISSUE THREAD

**Issue by elagina** [common-workflow-language/cwltool#1432]
Hello,

I am trying to use `--target` option with this very simple workflow

```
cwltool --target step2 --debug --print-subgraph wf.cwl > subgraph.cwl
```

However I get an error `TypeError: unhashable type: 'CommentedMap'`

Thanks!
---

## Expected Behavior
**subgraph.cwl**
```
{
    "class": "Workflow",
    "cwlVersion": "v1.2",
    "id": "file:///home/wf.cwl",
    "inputs": [
        {
            "id": "file:///home/wf.cwl#step2_in",
            "type": "string"
        }
    ],
    "outputs": [
        {
            "id": "file:///home/wf.cwl#step2_out",
            "outputSource": "file:///home/wf.cwl#step2/output",
            "type": "File"
        }
    ],
    "steps": [
        {
            "id": "file:///home/wf.cwl#step2",
            "in": [
                {
                    "id": "file:///home/wf.cwl#step2/in",
                    "source": "file:///home/wf.cwl#step2_in"
                }
            ],
            "out": [
                {
                    "id": "file:///home/wf.cwl#step2/output"
                }
            ],
            "run": "file:///home/echo.cwl"
        }
    ]
}
```

## Actual Behavior
Fails with the error as seen in  [Full Traceback](#traceback)

## Workflow Code
**wf.cwl**
```
class: Workflow
cwlVersion: v1.2
inputs:
  - id: step1_in
    type: string
  - id: step2_in
    type: string
outputs:
  - id: step1_out
    type: File
    outputSource: step1/output
  - id: step2_out
    type: File
    outputSource: step2/output
steps:
  - id: step1
    in:
      - id: in
        source: step1_in
    out:
      - id: output
    run: echo.cwl
  - id: step2
    in:
      - id: in
        source: step2_in
    out:
      - id: output
    run: echo.cwl
```
**echo.cwl**
```
cwlVersion: v1.2
class: CommandLineTool
baseCommand: echo
inputs:
  - id: in
    type: string
    inputBinding: {position: 1}
outputs:
  - id: output
    type: stdout
stdout: output_echo.txt
```
**wf.yml**
```
step1_in: step1
step2_in: step2
```

## Full Traceback

<a name="traceback"/>

```
Traceback (most recent call last):
  File "/home/miniconda/envs/cwl_env/lib/python3.8/site-packages/cwltool/main.py", line 1020, in main
    ctool = choose_target(args, tool, loadingContext)
  File "/home/miniconda/envs/cwl_env/lib/python3.8/site-packages/cwltool/main.py", line 768, in choose_target
    extracted = get_subgraph(
  File "/home/miniconda/envs/cwl_env/lib/python3.8/site-packages/cwltool/subgraph.py", line 83, in get_subgraph
    declare_node(nodes, out, None)
  File "/home/miniconda/envs/cwl_env/lib/python3.8/site-packages/cwltool/subgraph.py", line 41, in declare_node
    if nodeid in nodes:
TypeError: unhashable type: 'CommentedMap' 
```
When I am printing out the `nodeid` that is passed to `declare_node` function I see `CommentedMap` instead of `string`:
```
ordereddict([('id', 'file:///home/wf.cwl#step1/output')])
```
After I changed this lines 96-97 in [subgraph.py](https://github.com/common-workflow-language/cwltool/blob/main/cwltool/subgraph.py)
```
#declare_node(nodes, out, None)
declare_node(nodes, out["id"], None)
#nodes[out].up.append(st["id"])
nodes[out["id"]].up.append(st["id"])
```
I got the `subgraph.cwl` as shown above

## Your Environment
* cwltool version:  3.0.20201203173111
