### ISSUE TITLE
CommandLineTool output filenames are URL encoded

### ISSUE THREAD

**Issue by AlexTate** [common-workflow-language/cwltool#1445]
## Expected Behavior
CommandLineTool outputs whose filenames contain special characters should retain those special characters when copied to the final output directory. For example, if a CommandLineTool writes an output file with the name "(parentheses).txt", then the filename should remain "(parentheses).txt" when copied/moved to the final output directory.

## Actual Behavior
Filenames of CommandLineTool outputs are URL encoded after being copied/moved to the final output directory. For example, an output filename of "(parentheses).txt" becomes "%28parentheses%29.txt" in `command_line_tool.collect_output()`. 

## Cursory Analysis
This happens because `fs_access.glob()` returns a file URI, which is itself URL encoded, and `command_line_tool.collect_output()` properly calls `urllib.parse.unquote()` to obtain the URL decoded **path** but fails to do so for the **basename** and **nameroot** fields. This record's **basename** is then used as the destination name for outputs copied/moved to final output directory.

### url_encode_test.cwl
```
class: CommandLineTool
cwlVersion: v1.0

requirements: 
    - class: InlineJavascriptRequirement

baseCommand: touch

inputs:
    inp:
        type: string
        inputBinding:
            position: 0
outputs:
    out_file:
        type: File
        outputBinding:
            glob: $(inputs.inp)
```

### job.json
`{"inp": "(parentheses).txt"}`

## Full Traceback
N/A

## Your Environment
* cwltool version: 3.1.20210426140515
