### ISSUE TITLE
Request for cwltool to support named pipes

### ISSUE THREAD

**Issue by mhpopescu** [common-workflow-language/cwltool#1468]
## Expected Behavior
Some runners such as Toil might implement file streaming with named pipes when `streamable` flag is true:
https://github.com/DataBiosphere/toil/issues/3469

## Actual Behavior
An exception is raised because a named pipe is not a regular file:
https://github.com/common-workflow-language/cwltool/blob/ed9dd4c3472e940a52dfe90049895f470bfd7329/cwltool/job.py#L180

## Workflow Code
```
#!/usr/bin cwl-runner

cwlVersion: v1.2
class: CommandLineTool
baseCommand: cat

stdout: $(inputs.output_filename)
arguments: ["-A"]

inputs:
  input_file:
    type: File
    streamable: true
    inputBinding:
      position: 1
  output_filename:
    type: string?
    default: out.txt

outputs:
  count:
    type: stdout

```

## Your Environment
* cwltool version: 
3.0.20201203173111 (Linux)
