### ISSUE TITLE
Hints in CommandlineTool are not overridden by hints in Workflow Step 

### ISSUE THREAD

**Issue by alexiswl** [common-workflow-language/cwltool#1484]
## Expected Behavior

The hints in the workflow step should be prioritised over the hints in the commandline tool

## Actual Behavior
Tell us what happens instead

### Workflow
```yaml
cwlVersion: v1.1
class: Workflow

# Extensions
$namespaces:
    s: https://schema.org/
$schemas:
  - https://schema.org/version/latest/schemaorg-current-http.rdf

# Metadata
s:author:
    class: s:Person
    s:name: Alexis Lucattini
    s:email: Alexis.Lucattini@umccr.org
    s:identifier: https://orcid.org/0000-0001-9754-647X

requirements:
    InlineJavascriptRequirement: {}
    ScatterFeatureRequirement: {}
    MultipleInputFeatureRequirement: {}
    StepInputExpressionRequirement: {}

inputs:
  dummy_file_name:
    type: string

steps:
  get_dummy_file_step:
    hints:
      DockerRequirement:
        dockerPull: ubuntu:latest
    in:
      dummy_file_name:
        source: dummy_file_name
    out:
      - id: dummy_file_output
    run: create_dummy_file.cwl


outputs:
  dummy_file_out:
    type: File
    outputSource: get_dummy_file_step/dummy_file_output
```

### Tool
```yaml
cwlVersion: v1.1
class: CommandLineTool

# Extensions
$namespaces:
    s: https://schema.org/
$schemas:
  - https://schema.org/version/latest/schemaorg-current-http.rdf

# Metadata
s:author:
    class: s:Person
    s:name: Alexis Lucattini
    s:email: Alexis.Lucattini@umccr.org
    s:identifier: https://orcid.org/0000-0001-9754-647X

# ID/Docs
id: custom-create-dummy-file--1.0.0
label: custom-create-dummy-file v(1.0.0)
doc: |
    Documentation for custom-create-dummy-file v1.0.0

hints:
  DockerRequirement:
      dockerPull: alpine:latest

requirements:
  InlineJavascriptRequirement: {}

baseCommand: ["touch"]

inputs:
  dummy_file_name:
    label: file name
    doc: |
      Name of the file to create
    type: string
    default: "dummy_file.txt"
    inputBinding:
      position: 1

outputs:
  dummy_file_output:
    label: dummy file
    doc: |
      Output dummy file
    type: File
    outputBinding:
      glob: "$(inputs.dummy_file_name)"

successCodes:
  - 0
```

## Full Traceback
```pytb
$ cwltool --debug create_dummy_wf.cwl --dummy_file_name foo.txt
[1;30mINFO[0m /home/alexiswl/anaconda3/envs/cwltool/bin/cwltool 3.1.20210628163208
[1;30mINFO[0m Resolved 'create_dummy_wf.cwl' to 'file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_wf.cwl'
[1;30mINFO[0m ## DEBUG LOAD TOOL ##
[1;30mINFO[0m Workflow obj {'_yaml_line_col': LineCol(0, 0), '_yaml_format': <ruamel.yaml.comments.Format object at 0x7f85d7bfc580>}, fileuri file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_wf.cwl
[1;30mINFO[0m ## DEBUG LOAD TOOL END ##
[1;30mINFO[0m ## DEBUG WORKFLOW ##
[1;30mINFO[0m Uncommented map
[1;30mINFO[0m ## DEBUG WORKFLOW END ##
[1;30mINFO[0m ## DEBUG LOAD TOOL ##
[1;30mINFO[0m Workflow obj {'_yaml_line_col': LineCol(0, 0), '_yaml_format': <ruamel.yaml.comments.Format object at 0x7f85d6aa8ca0>}, fileuri file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_file.cwl
[1;30mINFO[0m ## DEBUG LOAD TOOL END ##
[1;30mDEBUG[0m [32mParsed job order from command line: {
    "id": "create_dummy_wf.cwl",
    "dummy_file_name": "foo.txt"
}[0m
[1;30mDEBUG[0m [32m[workflow ] initialized from file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_wf.cwl[0m
[1;30mINFO[0m [workflow ] start
[1;30mDEBUG[0m [32m[workflow ] inputs {
    "dummy_file_name": "foo.txt"
}[0m
[1;30mINFO[0m [workflow ] starting step get_dummy_file_step
[1;30mDEBUG[0m [32m[step get_dummy_file_step] job input {
    "file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_wf.cwl#get_dummy_file_step/dummy_file_name": "foo.txt"
}[0m
[1;30mDEBUG[0m [32m[step get_dummy_file_step] evaluated job input to {
    "file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_wf.cwl#get_dummy_file_step/dummy_file_name": "foo.txt"
}[0m
[1;30mINFO[0m [step get_dummy_file_step] start
[1;30mDEBUG[0m [32m[job get_dummy_file_step] initializing from file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_file.cwl#custom-create-dummy-file--1.0.0 as part of step get_dummy_file_step[0m
[1;30mDEBUG[0m [32m[job get_dummy_file_step] {
    "dummy_file_name": "foo.txt"
}[0m
[1;30mDEBUG[0m [32m[job get_dummy_file_step] path mappings is {}[0m
[1;30mDEBUG[0m [32m[job get_dummy_file_step] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "touch"
    },
    {
        "position": [
            1,
            "dummy_file_name"
        ],
        "datum": "foo.txt"
    }
][0m
[1;30mDEBUG[0m [32m[job get_dummy_file_step] initial work dir {}[0m
[1;30mINFO[0m [job get_dummy_file_step] /tmp/knwki8bl$ docker \
    run \
    -i \
    --mount=type=bind,source=/tmp/knwki8bl,target=/KtgqGj \
    --mount=type=bind,source=/tmp/xmi9l_po,target=/tmp \
    --workdir=/KtgqGj \
    --read-only=true \
    --net=none \
    --user=1000:1000 \
    --rm \
    --cidfile=/tmp/czargmnd/20210817102114-002297.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/KtgqGj \
    alpine:latest \
    touch \
    foo.txt
[1;30mINFO[0m [job get_dummy_file_step] Max memory used: 0MiB
[1;30mINFO[0m [job get_dummy_file_step] completed success
[1;30mDEBUG[0m [32m[job get_dummy_file_step] outputs {
    "dummy_file_output": {
        "location": "file:///tmp/knwki8bl/foo.txt",
        "basename": "foo.txt",
        "nameroot": "foo",
        "nameext": ".txt",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}[0m
[1;30mDEBUG[0m [32m[step get_dummy_file_step] produced output {
    "file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/create_dummy_wf.cwl#get_dummy_file_step/dummy_file_output": {
        "location": "file:///tmp/knwki8bl/foo.txt",
        "basename": "foo.txt",
        "nameroot": "foo",
        "nameext": ".txt",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}[0m
[1;30mINFO[0m [step get_dummy_file_step] completed success
[1;30mINFO[0m [workflow ] completed success
[1;30mDEBUG[0m [32m[workflow ] outputs {
    "dummy_file_out": {
        "location": "file:///tmp/knwki8bl/foo.txt",
        "basename": "foo.txt",
        "nameroot": "foo",
        "nameext": ".txt",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    }
}[0m
[1;30mDEBUG[0m [32m[job get_dummy_file_step] Removing input staging directory /tmp/97rlbj3w[0m
[1;30mDEBUG[0m [32m[job get_dummy_file_step] Removing temporary directory /tmp/xmi9l_po[0m
[1;30mDEBUG[0m [32mMoving /tmp/knwki8bl/foo.txt to /c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/foo.txt[0m
{
    "dummy_file_out": {
        "location": "file:///c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/foo.txt",
        "basename": "foo.txt",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "path": "/c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/scratches/foo.txt"
    }
}
[1;30mINFO[0m Final process status is success

```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``

```
cwltool 3.1.20210628163208
```
