### ISSUE TITLE
Bug in graph using `--print-dot`

### ISSUE THREAD

**Issue by ALuesink** [common-workflow-language/cwltool#1570]
## Expected Behavior
Using the command `cwltool --print-dot workflow.cwl | dot -Tsvg > wf.svg` to make a SVG file, a graph of the workflow.

## Actual Behavior
A SVG file is created and when viewing the graph, the _fastqc_ step isn't depicted as a box, but the location of the workflow is depicted. There is no error on the command line. 

![image](https://user-images.githubusercontent.com/22368429/143485296-1a012d8f-500c-4c40-a84c-1423fb332c1c.png)

## Workflow Code
```
cwlVersion: v1.2
class: Workflow
label: RNAseq CWL practice workflow

inputs:
  fq: File

steps:
  fastqc:
    run: bio-cwl-tools/fastqc/fastqc_2.cwl
    in:
      reads_file: fq
    out: [html_file]

outputs:
  qc_html:
    type: File
    outputSource: fastqc/html_file

```

## Full Traceback
```pytb
INFO /mnt/d/Documenten/School/Master/CWL_project/env_cwl/bin/cwltool 3.1.20211107152837
INFO Resolved 'fastqc.cwl' to 'file:///mnt/d/Documenten/School/Master/CWL_project/rnaseq-cwl-training-exercises/fastqc.cwl'
```

## Your Environment
* cwltool version: 3.1.20211107152837
Using a virtual environment with the latest cwltool version.
