### ISSUE TITLE
cwltool: Input of type Directory[] stays readonly if using writable: true in InitialWorkDirRequirement

### ISSUE THREAD

**Issue by adrabent** [common-workflow-language/cwltool#1633]
Dear cwltool developers.

## Expected Behavior

I created a CWL step that takes an input of type `Directory[]`. This step should be able to read-write on the input data. 

```
class: CommandLineTool
cwlVersion: v1.2

baseCommand:
  - aoflagger

inputs:
  - id: msin
    type:
      - Directory[]
    inputBinding:
      position: 1
      shellQuote: false

outputs:
  - id: output_ms
    doc: Output MS
    type:
      - Directory[]
    outputBinding:
      outputEval: $(inputs.msin)

requirements:
  - class: ShellCommandRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.msin)
        writable: true
hints:
  - class: DockerRequirement
    dockerPull: lofareosc/prefactor3-cwl
```
## Actual Behavior
What happens is this:
```
docker \
    run \
    -i \
    --mount=type=bind,source=/home/alex/CI_test/tmp/erf4tmzv,target=/qdACiA \
    --mount=type=bind,source=/home/alex/CI_test/tmp/n8nqegdi,target=/tmp \
    --mount=type=bind,source=/home/alex/CI_test/tmp/ium2zv4a/out_L667520_121MHz_uv.dpppconcat,target=/qdACiA/out_L667520_121MHz_uv.dpppconcat,readonly \
    --mount=type=bind,source=/home/alex/CI_test/tmp/i057buav/out_L667520_123MHz_uv.dpppconcat,target=/qdACiA/out_L667520_123MHz_uv.dpppconcat,readonly \
    --workdir=/qdACiA \
    --net=none \
    --log-driver=none \
    --user=1067:200 \
    --rm \
    --cidfile=/home/alex/CI_test/tmp/9whm9aoz/20220303150355-992717.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/qdACiA \
    lofareosc/prefactor3-cwl \
    /bin/sh \
    -c \
    'aoflagger' '/qdACiA/out_L667520_121MHz_uv.dpppconcat' '/qdACiA/out_L667520_123MHz_uv.dpppconcat' 
```
Plus this error message:
```
  what():  RegularFileIO: error in open or create of file /qdACiA/out_L667520_123MHz_uv.dpppconcat/table.dat: Read-only file system
Aborted (core dumped)
```

I would expect that the data mounted to the working directory is not set **readonly**, but it is.

The cwltool version is: 3.1.20220224085855

-- Alex
