### ISSUE TITLE
Incorrect validation warning  when combining "scatter" and "when"

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwltool#1639]
## Expected Behavior
Should not give a warning when scattering with a conditional connects to an array of optional values.

## Actual Behavior
It gaves a warning because the output type is computed incorrectly for the order of operations in a step that has both a scatter and a conditional.

## Workflow Code

```
steps:
  fastq-validator:
    run: tools/fastqValidator.cwl
    in:
      file:
        - fastq1
        - fastq2
    out: [std_out]
    scatter: file
    when: $(inputs.file != null)

  adjust-names:
    in:
      sample_name: sample_name
      fqValidator: 50-fastq-validator/std_out
    out: [fq1, fq2]
    run: adjust-names.cwl
```

```
workflow.cwl:21:11: Source 'std_out' of type ["null", {"type": "array", "items": "File"}] may be
                    incompatible
workflow.cwl:28:7:    with sink 'fqValidator' of type {"type": "array", "items": ["null", "File"]}
                      Source is from conditional step and may produce `null`
```
The checker is using the wrong type for `fastq-validator/std_out`, it should be {"type": "array", "items": ["null", "File"]}.

## Your Environment
cwltool 3.1.20220221215214
