### ISSUE TITLE
Field is not valid: CommentedSeq expected null or string

### ISSUE THREAD

**Issue by jjkoehorst** [common-workflow-language/cwltool#1673]
## Expected Behavior
When providing a YAML with a list variable to an entry that requires an optional string should throw an error stating that a list was provided and that a null or string was expected.

## Actual Behavior
It complains about a CommentedSeq value while its actually a list.

```
QUALITY.yaml:7:1: the `kraken_database` field is not valid 
because value is a CommentedSeq, expected null or string
```

## Workflow Code
```
  kraken_database:
    type: string?
    label: Kraken2 database
    doc: Kraken2 database location
    default: "/unlock/references/databases/Kraken2/K2_PlusPF_20210517"
```

## Your Environment
* cwltool version: INFO /usr/local/bin/cwltool 3.1.20220520101121
