### ISSUE TITLE
Auto-casting single item to array fails if array is optional

### ISSUE THREAD

**Issue by briandoconnor** [common-workflow-language/cwltool#171]
Input

```
  inputFileName_markDups:
    type: File[]?
    inputBinding:
      position: 4
      prefix: INPUT=
```

The call uses a *single* BAM file from a previous step, not an array.

Causes the following error:

```
Workflow error, try again with --debug for more information:
  Type mismatch between source 'file:///home/ubuntu/gitroot/common-workflow-language/workflows/workflows/GATK/GATK-complete-Workflow-h3abionet.cwl#samtools-sort/sorted' (File) and sink 'file:///home/ubuntu/gitroot/common-workflow-language/workflows/workflows/GATK/GATK-complete-Workflow-h3abionet.cwl#MarkDuplicates/inputFileName_markDups' ([u'null', {u'items': 'File', u'type': u'array'}])
```

But it works fine when markdup's input is:

```
  inputFileName_markDups:
    type: File[]
    inputBinding:
      position: 4
      prefix: INPUT=
```
