### ISSUE TITLE
CWLProv: secondary files missing from RO

### ISSUE THREAD

**Issue by simleo** [common-workflow-language/cwltool#1751]
Workflow: [predictions.cwl](https://github.com/simleo/deephealth-pipelines/tree/3037aa6e2e1795268cf52f4170850bab8c3e4b54/cwl). Job file:

```yaml
slide:
  class: File
  path: data/Mirax2-Fluorescence-2.mrxs
tissue-low-level: 9
tissue-low-label: tissue_low
tissue-high-level: 4
tissue-high-label: tissue_high
tissue-high-filter: tissue_low>0.9
gpu: null
tumor-level: 1
tumor-label: tumor
tumor-filter: tissue_low>0.99
```

The input file is https://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/Mirax2-Fluorescence-2.zip. Unpacking the archive generates the `Mirax2-Fluorescence-2.mrxs` listed in the job file and a `Mirax2-Fluorescence-2` directory containing auxiliary files. The job completes successfully, indicating that the `secondaryFiles` fields in the tools are working. However, [the RO](https://github.com/simleo/workflow-run-crate/tree/4984773de53b67e6af047f9dc34297c76b4cc165/tools/cwlprov_to_crate/test/data/predictions-run-1) does not contain the auxiliary files, and they are not recorded in the provenance files.
