### ISSUE TITLE
Problem with when statements in the workflow: nonetype input for scatter

### ISSUE THREAD

**Issue by monigenomi** [common-workflow-language/cwltool#1800]
I have 2 following steps in CWL workflow that are executed conditionally (using when statement) and output from one of them is input for the second one, and second one contains scatter. There is a fragment of code here:

```
steps:
  list_fastqs_from_dirs_with_ngs_data:
    run: ../shared_tools/collections2files/collections2files.cwl
    when: $(inputs.run_step === true)
    in:
      dirs: dirs_with_ngs_data
      run_step: run_sort_fastq
    out: [files]
  
  sort_fastq:
    run: ./sort_fastq/sort_fastq.cwl
    when: $(inputs.run_sort_fastq === true)
    in:
      fastq_file: list_fastqs_from_dirs_with_ngs_data/files
      run_sort_fastq: run_sort_fastq
    scatter: fastq_file
    out: [sorted_fastq]
```

When I run the pipeline and `run_sort_fastq === true` pipeline is completed.
But when `run_sort_fastq === false` pipeline fails, because scatter is empty:

```
ERROR Unhandled exception
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/cwltool/workflow_job.py", line 730, in try_make_job
    emptyscatter = [
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/cwltool/workflow_job.py", line 731, in <listcomp>
    shortname(s) for s in scatter if len(cast(Sized, inputobj[s])) == 0
TypeError: object of type 'NoneType' has no len()
```
It should not matter that scatter is empty, because `sort_fastq` step is not executed.
I fixed the problem, using dummy input 'blank_input' in `sort_fastq` with the same input type than `list_fastqs_from_dirs_with_ngs_data/files` that is always not empty. The code with solution looks like that:

```
fastq_file:
        source: [list_fastqs_from_dirs_with_ngs_data/files, blank_input]
        pickValue: first_non_null 
```
and works.

Exactly the same problem also exists in arvados-cwl-runner, which I described here: https://cwl.discourse.group/t/problem-with-when-statements-in-the-workflow-with-nonetype-input-for-scatter/749/1

cwltool version: 3.1.20230127121939

Could you look into this please?

**Comment by tetron** [comment]
I'm curious, does this work as a workaround?

```
    in:
      fastq_file:
        source: list_fastqs_from_dirs_with_ngs_data/files
        default: []
```

I assume `list_fastqs_from_dirs_with_ngs_data` was skipped, so `list_fastqs_from_dirs_with_ngs_data/files` is `null`.  So it is trying to scatter over `null`

So, there's two problems.

1. It isn't obvious, but `scatter` is evaluated _before_ `when`.  This was to make it possible to scatter over a list and have some scatter steps run, and others to be skipped.  That's why what you expected to happen (peeking at `when` and skipping everything) doesn't happen.
2. The spec says "connected values must be arrays", so it's arguably correct to fail on a non-array value. 

However the fact that it crashes instead of raising an error means this is more of an oversight that a intentional decision.

I think there's a couple of options.

1. Fix the crash but don't do anything else, this code still doesn't work, but it gives a more meaningful error.
2. Specify the `scatter: null` case is equivalent to empty list and produce empty list outputs
3. Specify the `scatter: null` case is equivalent to `when: false` and produce `null` outputs

I'm leaning towards the 3rd option as the most desirable behavior, but to properly deal with it will require not just a code fix but a spec clarification with a new conformance test.

**Comment by monigenomi** [comment]
@tetron - the workaround solution you suggested works:

```
in:
  fastq_file:
     source: list_fastqs_from_dirs_with_ngs_data/files
     default: []
```
