### ISSUE TITLE
loadContents is limited to 65536 bytes.

### ISSUE THREAD

**Issue by ndonyapour** [common-workflow-language/cwltool#2075]
I have a tool that generates a log file, and I want to load its content. However, the load content is currently limited to 65,536 bytes. This limitation is hard-coded at [this line](https://github.com/common-workflow-language/cwltool/blob/e4d42b85d24cd5088e14cc31d67c2dee0c6fc40a/cwltool/utils.py#L61).

Would it be possible to add an option that lets users set this value? 

Thanks,
Nazanin

**Comment by mr-c** [comment]
Hello @ndonyapour , that limit is a requirement of the CWL standards.


https://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineBinding

If you need to access a bigger file, I just writing a small shell or Python script inside a `CommandLineTool`.

**Comment by EmileSonneveld** [comment]
I also got this strange limit, and wrote this logic to work around it:
```yaml
cwlVersion: v1.2
class: Workflow

inputs:
  input_file:
    type: File

outputs:
  file_content:
    type: string
    outputSource: read_file/contents

steps:
  read_file:
    in:
      file: input_file
    out: [ contents ]
    run:
      # A CommandLineTool is used (instead of an ExpressionTool with
      # loadContents) so that cwltool's normal file-staging mechanism
      # downloads remote (http/https) File inputs before reading them.
      # ExpressionTool + loadContents reads the file itself via
      # StdFsAccess, which cannot open remote URLs.
      #
      # The file's contents are also read by a small Python script
      # (as suggested in https://github.com/common-workflow-language/cwltool/issues/2075)
      # which writes them to cwl.output.json. cwltool parses that file
      # with a plain json.load, bypassing the 64 KiB loadContents cap
      # that the CWL spec otherwise imposes, so this also works for
      # files/pages larger than 64 KiB.
      class: CommandLineTool
      baseCommand: python3
      inputs:
        file:
          type: File
      outputs:
        contents:
          type: string
      arguments:
        - "-c"
        - valueFrom: |
            import json
            with open("$(inputs.file.path)", "r", errors="replace") as f:
                content = f.read()
            with open("cwl.output.json", "w") as f:
                json.dump({"contents": content}, f)
```
`cwltool file-to-string.cwl --input_file https://google.com/index.html`
