### ISSUE TITLE
cwltool truncates numbers < 1e-6 to zero when placing them on the command line

### ISSUE THREAD

**Issue by sebitz** [common-workflow-language/cwltool#2104]
test_tool.cwl:
```yaml
class: CommandLineTool
inputs:
  float:
    type: float
    default: 1e-6
    inputBinding:
      position: 1
  double:
    type: double
    default: 9.999e-7
    inputBinding:
      position: 2
outputs:
  numbers: stdout
baseCommand: [ printf, '%s\n' ]
stdout: my_numbers.txt
```
Running `cwltool --disable-color --debug test_tool.cwl >test_tool.out.json 2>test_tool.err.txt` produces `my_numbers.txt`. However, it contains:
```
0.000001
0
```

Whereas I expected it to look like this:
```
0.000001
0.0000009999
```

The results are the same with scientific or decimal notation, with `type: float` or `type: double`, job inputs in a .json or a .yaml file. Curiously enough, it seems to behave correctly if I pass the numbers on the command line, e.g., `cwltool test_tool.cwl --float 1e-6 --double 9.999e-7` gives
```
1e-06
9.999e-07
```

From
[test_tool.err.txt](https://github.com/user-attachments/files/19009774/test_tool.err.txt) I can see that the command line bindings are correct `datum: 9.999e-07` and `datum: 1e-06`. However, the actual command line read `printf %s\n 0.000001 0` instead of `printf %s\n 0.000001 0.0000009999`.

**Comment by sebitz** [comment]
I think I have a workaround. Unfortunately it needs [`InlineJavascriptRequirement`](https://www.commonwl.org/v1.2/CommandLineTool.html#InlineJavascriptRequirement).

The workaround is:
```yaml
requirements:
- class: InlineJavascriptRequirement
inputs:
  number:
    type: [ float, double ]
    inputBinding:
      valueFrom: $(self * 1.0)
```

Probably `$(self + 0.0)` would work just as well, but I haven't tried it.
