### ISSUE TITLE
synthetic files from InitialWorkDirRequirement not created or staged

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#242]
``` yaml
class: CommandLineTool
cwlVersion: v1.0
baseCommand: [ls, -l]
requirements:
  InitialWorkDirRequirement:
    listing:
      - entryname: fancy-input.json
        entry: $(inputs.fancy)
inputs:
  fancy:
    type:
      type: record
      fields:
        - name: one
          type: string
        - name: two
          type: int
        
outputs:
  outfile:
    type: stdout
```

**Comment by mr-c** [comment]
The CWL above is incorrect, as expression passed to `entry` must return one of a string, Directory, or a File:
http://www.commonwl.org/v1.0/CommandLineTool.html#Dirent

The following works as intended:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [cat, fancy-input.json]
requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing:
      - entryname: fancy-input.json
        entry: $(JSON.stringify(inputs.fancy))
inputs:
  fancy:
    type:
      type: record
      fields:
        - name: one
          type: string
        - name: two
          type: int
        
outputs:
  outfile:
    type: stdout
```
