### ISSUE TITLE
Scope of StepInput Expressions

### ISSUE THREAD

**Issue by karl616** [common-workflow-language/cwltool#252]
I spend some hours yesterday in order to detect that StepInputExpressions:

```
inputs:
  input1: string

steps:
  step1:
    in:
      argument1:
        valueFrom: $(...)
      argument2:
        source: "#input1"
```

doesn't have access to the input variables. I was furiously trying to refer them by inputs.input1, changing everything around this, assuming the error resided elsewhere. In the end I understood I had to add the required variables as additional input. It makes total sense to have it like that. I have nothing against it, but I would wish it to be explained better in the documentation.

I read the WorkflowStepInput/Fields/valueFrom again. Knowing how it works, I can parse the definition, but I missed it earlier. 

In hindsight, this is obviously a mistake on my side. If anything it boils down to a wish for clearer user documentation, perhaps an extension of the gentle introduction to include more of the nitty-gritty details.
