### ISSUE TITLE
Unhandled exception when scattering over a Directory.listing

### ISSUE THREAD

**Issue by undu** [common-workflow-language/cwltool#279]
There are two problems that seem to be happening:
1. cwltool doesn't generate the `listing` property for `Folder`s in the inputs.
2. this leads to a null reference in python which leads to the unhandled exception:
```
$ cwltool textures.cwl jobs/textures-job.yml
/home/undu/.config/virtualenvs/cwl/bin/cwltool 1.0.20170118141124
Resolved 'textures.cwl' to 'file:///home/undu/dev/stellaris-emblem-lab/textures/scripts/textures.cwl'
[job gradients] /tmp/tmpSLaHnL$ sh \
    /tmp/tmp5oPppp/stg48a9ed53-e751-46f3-bd3d-74c9994398c2/gradients_gen.sh
[job gradients] completed success
[step gradients] completed success
Unhandled exception
Traceback (most recent call last):
  File "/home/undu/.config/virtualenvs/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 306, in try_make_job
    Callable[[Any], Any],callback), **kwargs)
  File "/home/undu/.config/virtualenvs/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 636, in dotproduct_scatter
    l = len(joborder[s])
TypeError: object of type 'NoneType' has no len()
[workflow textures.cwl] outdir is /tmp/tmpxbhiuz
{}
Final process status is permanentFail
```
Problem can be reproduced with [this repository](https://www.gitlab.com/unduthegun/stellaris-emblem-lab/tree/027c86bf9c147a7de3ba048a8dc158256b887b7f/textures/scripts), the command should be run in the linked repository and commit.

**Comment by michael-kotliar** [comment]
1. In **_textures.cwl_** for the step **_textures_** you have input with id **_outlines_**, when the actual input id inside **_texture_emblem.cwl_** is **_outline_**
2. I'm not quite sure how scatter suppose to work in your implementation, but I assumed that adding the intermediate_step will help you to do the same:
```
  intermediate_step:
    in:
      folder: outlines_new
    out: [file_array]
    run:       
      class: ExpressionTool
      id: "intermediate_step"
      inputs:  
        folder: Directory
      outputs: 
        file_array: File[]
      expression: |
        ${
          var file_array = inputs.folder.listing;
          return { "file_array": file_array };
        }

  textures:
    run: texture_emblem.cwl
    scatter: outline
    in:
      outline: intermediate_step/file_array
      fill_gradient: gradients/fill_gradient
      highlight_gradient: gradients/highlight_gradient
    out: [texture_default, texture_map, texture_small] 
```
3. When running with **_intermediate_step_** I passed that error, that you had, but got another one somewhere inside step **_map_** from **_texture_emblem.cwl_**

```
[workflow textures] starting step map
[job step map] job input {
    "file:///Users/kot4or/Downloads/stellaris/textures/scripts/texture_emblem.cwl#map/outline": {
        "basename": "batman_classic.png", 
        "class": "File", 
        "location": "file:///Users/kot4or/Downloads/stellaris/img/batman_classic.png"
    }, 
    "file:///Users/kot4or/Downloads/stellaris/textures/scripts/texture_emblem.cwl#map/file_name": null
}
Unhandled exception
```
Hope it will help you to make your workflow work

**Comment by undu** [comment]
Thanks for the help. Unfortunately I'm getting the same error even when fixing (1) and adding the intermediate step.

```
/home/pau/.config/virtualenvs/cwl/bin/cwltool 1.0.20170119234115
Resolved 'textures.cwl' to 'file:///home/pau/dev/stellaris/emblem-lab/textures/scripts/textures.cwl'
[step extractListing] completed success
[job gradients] /tmp/tmp54xPXZ$ sh \
    /tmp/tmpuLQYb7/stg2915bac3-ac72-488e-85d5-b5214dddc813/gradients_gen.sh
[job gradients] completed success
[step gradients] completed success
Unhandled exception
Traceback (most recent call last):
  File "/home/pau/.config/virtualenvs/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 306, in try_make_job
    Callable[[Any], Any],callback), **kwargs)
  File "/home/pau/.config/virtualenvs/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 636, in dotproduct_scatter
    l = len(joborder[s])
TypeError: object of type 'NoneType' has no len()
[workflow textures.cwl] outdir is /tmp/tmpuXrAfB
{}
Final process status is permanentFail
```

**Comment by michael-kotliar** [comment]
Try this code instead of your **textures.cwl** (or compare with your changes). In my case I passed your error and found another one inside **texture_emblem.cwl**. I used that commit, that you linked in your original issue.

```yaml
cwlVersion: v1.0
doc: Create emblem textures
class: Workflow
requirements:
  - class: ScatterFeatureRequirement
  - class: SubworkflowFeatureRequirement
  - class: InlineJavascriptRequirement
  - class: StepInputExpressionRequirement

inputs:
  outlines: File[]
  outlines_new: Directory

outputs:
  texture_map:
    type: Directory[]
    outputSource: organize/folders

steps:
  gradients:
    run: tools/gradients_gen.cwl
    in: []
    out: [fill_gradient, highlight_gradient]

  intermediate_step:
    in:
      folder: outlines_new
    out: [file_array]
    run:       
      class: ExpressionTool
      id: "intermediate_step"
      inputs:  
        folder: Directory
      outputs: 
        file_array: File[]
      expression: |
        ${
          var file_array = inputs.folder.listing;
          return { "file_array": file_array };
        }

  textures:
    run: texture_emblem.cwl
    scatter: outline
    in:
      outline: intermediate_step/file_array
      fill_gradient: gradients/fill_gradient
      highlight_gradient: gradients/highlight_gradient
    out: [texture_default, texture_map, texture_small] 

#  textures:
#    run: texture_emblem.cwl
#    scatter: outlines
#    in:
#      outlines_dir: outlines_new
#      outlines:
#        valueFrom: $(inputs.outlines_dir.listing)
#      fill_gradient: gradients/fill_gradient
#      highlight_gradient: gradients/highlight_gradient
#    out: [texture_default, texture_map, texture_small]

  # Move textures in their respective folders
  organize:
    in:
      default: textures/texture_default
      map: textures/texture_map
      small: textures/texture_small
    out: [folders]
    run:
      class: ExpressionTool
      id: "organize"
      inputs:
        map: File[]
      outputs:
        folders: Directory[]
      expression: |
        ${
          var folders = [];
          folders.push({
            "class": "Directory",
            "basename": "out",
            "listing": inputs.default
          });
          folders.push({
            "class": "Directory",
            "basename": "out/map",
            "listing": inputs.map
          });
          folders.push({
            "class": "Directory",
            "basename": "out/small",
            "listing": inputs.small
          });
          return { "folders": folders };
        }

```
