### ISSUE TITLE
InitialWorkDirRequirement mounts inputdir as ro

### ISSUE THREAD

**Issue by Jeltje** [common-workflow-language/cwltool#295]
In the example below, the directory that contains `$(inputs.reference)` is mounted as `ro` on the docker container, leading to failure:

CWL (snippet,  [full file here](https://github.com/common-workflow-language/cwltool/files/783983/my_pileup.cwl.txt)):
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ["samtools", "mpileup"]
requirements:
  - class: "DockerRequirement"
    dockerImageId: "opengenomics/samtools_pileup:1.1.2"
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - $(inputs.reference)

inputs: 

  - id: "#reference"
    type: File
    inputBinding:
      prefix: -f
(...)
```
Command: `cwltool --non-strict my_pileup.cwl samtools.json`
version:
`cwltool (1.0.20170217172322)`

Error (snippets, [full log here](https://github.com/common-workflow-language/cwltool/files/783984/initWdir_err.txt)):
```
docker \
    run \
    -i \
    --volume=/mnt/data/muse_smalltest/chr17.fa:/var/lib/cwl/stg15a69f84-cda5-4336-b695-320347867ca9/chr17.fa:ro \
    --volume=/mnt/data/muse_smalltest/normal.bam:/var/lib/cwl/stge820dd20-82ba-4f11-a3d5-d038d2c87c6a/normal.bam:ro \
    --volume=/tmp/tmp0frAFb:/var/spool/cwl:rw \
    --volume=/tmp/tmp8Z6wYP:/tmp:rw \
(...)
[fai_build] fail to write FASTA index /var/lib/cwl/stg15a69f84-cda5-4336-b695-320347867ca9/chr17.fa.fai
```

**Comment by mr-c** [comment]
Hello @Jeltje 

Thank you for reporting your issue.

You'll need to mark the input as being writable:

``` yaml
requirements:
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.reference)
        writable: true
```

Additionally you have some errors in your CWL, looks like this used to be in the draft-3 syntax
1. the `description` field was renamed to `doc` in CWL v1.0.
2. `secondaryFiles` is now moved out of `inputBinding`

Fixing those removes the need for `--non-strict`. If you need to upgrade additional draft-3 syntax files to v1.0 I recommend using the [cwl-upgrader](https://github.com/common-workflow-language/cwl-upgrader)

Making the following changes would simplify this description:
1. Removing the unused `InlineJavascriptRequirement`
2. Using the short form syntax whenever possible
3. Removing unneeded quotes and `#`.
4. Moving the `DockerRequirement` under `hints:` so the description is usable without Docker.
5. Renaming the input named `input` to `alignments` and the output named `output` to `pileup` to be more meaningful
6. Using the `type: stdout` shortcut
7. Adding `?` to the end of the input types that have default values.

Here is what that looks like all together:
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

requirements:
  InitialWorkDirRequirement:
    listing: 
      - entry: $(inputs.reference)
        writable: true
hints:
  DockerRequirement:
    dockerImageId: opengenomics/samtools_pileup:1.1.2

label: SamTools Pileup
baseCommand: [samtools, mpileup]
# samtools mpileup  -B  -q 1  -f reference.fa > output

inputs:
  noBaq:
    type: boolean?
    doc: disable BAQ (per-Base Alignment Quality)
    default: false
    inputBinding:
      prefix: -B

  minMapQ:
    doc:   -q, --min-MQ INT        skip alignments with mapQ smaller than INT [0]
    type: int?
    default: 0
    inputBinding:
      prefix: -q
  
  reference:
    type: File
    inputBinding:
      prefix: -f
#      secondaryFiles:
#        - .fai

  alignments:
    type: File
    inputBinding:
      position: 1
    secondaryFiles:
      - .bai

stdout: output.pileup

outputs:
  pileup:
    type: stdout
```
