### ISSUE TITLE
Should enums with identical structure but defined in separate locations be considered the same type? 

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/cwltool#308]
Hi all!
Found `Type mismatch between source and sink` when trying to pass enum from workflow to task.
To run the workflow: `cwl-runner --debug workflow.cwl job.json`

**workflow.cwl**
```yaml
class: Workflow
cwlVersion: v1.0

requirements:
  - class: StepInputExpressionRequirement

inputs:

  enum_workflow_input:
    type:
      name: "foo"
      type: enum
      symbols: ["a","b","c"]

outputs: []

steps:
  task:
    in:
      enum_task_input: enum_workflow_input
    out: []
    run: task.cwl
```
**task.cwl**
```yaml
class: CommandLineTool
cwlVersion: v1.0
inputs:

  enum_task_input:
    type:
      name: "foo"
      type: enum
      symbols: ["a","b","c"]

outputs: []

arguments: [echo, $(inputs.enum_task_input) ]
```
**job.json**
```json
{
  "enum_workflow_input": "b"
}
```
Output log
```
/home/michael_kotliar/.local/bin/cwl-runner 1.0.20170224141733
Resolved 'workflow.cwl' to 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl'
[workflow workflow.cwl] initialized from file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl
[workflow workflow.cwl] workflow starting
[step task] Cannot make job: Type mismatch between source 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input' (ordereddict([('name', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo'), ('type', 'enum'), ('symbols', [u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo/a', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo/b', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo/c'])])) and sink 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#task/enum_task_input' (ordereddict([('name', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo'), ('type', 'enum'), ('symbols', [u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo/a', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo/b', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo/c'])]))

Traceback (most recent call last):
  File "/home/michael_kotliar/python/lib/python2.7/site-packages/cwltool/workflow.py", line 391, in job
    for newjob in step.iterable:
  File "/home/michael_kotliar/python/lib/python2.7/site-packages/cwltool/workflow.py", line 264, in try_make_job
    self.state, inputparms, False, supportsMultipleInput, "source")
  File "/home/michael_kotliar/python/lib/python2.7/site-packages/cwltool/workflow.py", line 174, in object_from_state
    inp["type"]))
WorkflowException: Type mismatch between source 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input' (ordereddict([('name', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo'), ('type', 'enum'), ('symbols', [u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo/a', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo/b', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#enum_workflow_input/foo/c'])])) and sink 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/workflow.cwl#task/enum_task_input' (ordereddict([('name', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo'), ('type', 'enum'), ('symbols', [u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo/a', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo/b', u'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/cwl_sandbox/enum/task.cwl#enum_task_input/foo/c'])]))
[workflow workflow.cwl] outdir is /tmp/tmppOsPjo
Removing intermediate output directory /tmp/tmppOsPjo
{}
Final process status is permanentFail
```

**Comment by qiukunlong** [comment]
I met this too. Is this fixed?

**Comment by serge2016** [comment]
Hello! Anybody here? I have the same behavior:
1. A tool with non-required enum input.
2. A Workflow with the same enum input to pass it to the step --> tool.
Only while such inputs are not required the validation is passed (with warnings), but if I make this input required, then it's a validation error. It seems to me, that symbols inside the enum should not be converted to URIs, they should stay unchanged in the enum tpye.

**Comment by mr-c** [comment]
Hello all,

Sorry for the delay. I invite @tetron and @stian to discuss if this is a bug or not.

One approach is to externalize the type definition and import it into each CWL document that needs to refer to it:

enum.yaml
``` yaml
name: foo
type: enum
symbols: [a, b, c]
```

enum-task.cwl
``` yaml
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

requirements:
  SchemaDefRequirement:
    types:
     - $import: enum.yaml

inputs:
  enum_task_input: enum.yaml#foo

outputs: []

arguments: [echo, $(inputs.enum_task_input) ]
```

enum-workflow.cwl
``` yaml
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow

requirements:
  StepInputExpressionRequirement: {}
  SchemaDefRequirement:
    types:
     - $import: enum.yaml

inputs:
  enum_workflow_input: enum.yaml#foo

outputs: []

steps:
  task:
    in:
      enum_task_input: enum_workflow_input
    out: []
    run: enum-task.cwl
```

``` bash
$ cwltool --validate enum-workflow.cwl 
/home/michael/cwltool/env/bin/cwltool 1.0.20171205210500
Resolved 'enum-workflow.cwl' to 'file:///home/michael/cwltool/enum-workflow.cwl'
Tool definition is valid
```

Here is the relevant section of the user guide (which did not exist when this question was originally asked): http://www.commonwl.org/user_guide/19-custom-types/
