### ISSUE TITLE
higher precedence to user assigned positions instead of non-assigned positions

### ISSUE THREAD

**Issue by kapilkd13** [common-workflow-language/cwltool#316]
when assigning positions to input field in cwl file, there may occur a case where some inputs are not assigned a position. It seems that all those unassigned fields get 0 position assigned to them. Users usually start assigning position from 1 and thus they come after unassigned fields. Since a user has explicitly mentioned a position, according to me they should get higher precedence than unassigned fields. 
for ex.
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  example_flag:
    type: boolean
    inputBinding:
      
      prefix: -f
  example_string:
    type: string
    inputBinding:
      position: 1
      prefix: --example-string
  example_int:
    type: int
    inputBinding:
      
      prefix: -i
      separate: false


outputs: [] 
```

should produce(as per me)
` --example-string hello -f -i42
 `
but it produces
` -f -i42 --example-string hello
 `
here input file is:
```
example_flag: true
example_string: hello
example_int: 42
 ```
It may be that its a functionality rather than a bug, in that case we would update documentation and mention this behaviour.
