### ISSUE TITLE
inputBinding.valueFrom for File[] is appending items instead of replacing the input value

### ISSUE THREAD

**Issue by gmetzker** [common-workflow-language/cwltool#329]
For reference I'm using OSX, Python 2.7.12, and cwltool v1.0.20170224141733

I'm trying to wrap a `zip` command with multiple files as input.  The input to the job is just an array of source files.  The goal is to have the source files at the root of the resulting zip with no sub-directories.

By default when the command is rendered it passes the input files with some sort of temporary path like `/private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpSJzLPX/stg767105dc-13b4-403d-8663-4c6c6133d663/hello.txt`  This results in a zip file that contains a long nested folder.

My solution is to use `InitialWorkDirRequirement` to stage the input files in the output folder [as documented here](http://www.commonwl.org/v1.0/UserGuide.html#Staging_input_files_in_the_output_directory).  I can get this to work if my input is a single file to zip but if I want to use an array of files then I'm having difficulty.

To stage multiple input files I'm using `valueFrom` in the `inputBinding` with a java script expression that iterates the inputs and returns an array with just the base file name.

**params.yaml**
```YAML
zipFileName: myzip.zip
srcFiles:
   - class: File
     path: hello.txt
   - class: File
     path: bye.txt
```

**zip-cwl**
```YAML
cwlVersion: v1.0
class: CommandLineTool
baseCommand: zip

requirements:

  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing: $(inputs.srcFiles)

inputs:

  zipFileName:
    type: string
    inputBinding:
      position: 1

  srcFiles:
    type: File[]
    inputBinding:
      separate: false
      position: 2
      valueFrom: |
        ${
          var r = [];
          for(var i=0; i < self.length; i++) {
            r.push(self[i].basename);
          }
          return r;
        }

outputs:
  zipFile:
    type: File
    outputBinding:
      glob: $(inputs.zipFileName)

```
**Directory Stucture**
```
$ ls -ls
total 32
8 -rw-r--r--  1 gmetzker  staff   18 Mar  9 16:11 bye.txt
8 -rw-r--r--  1 gmetzker  staff   17 Mar  9 16:09 hello.txt
8 -rw-r--r--  1 gmetzker  staff  107 Mar  9 19:08 params.yaml
8 -rw-r--r--  1 gmetzker  staff  615 Mar  9 19:08 zip-files.cwl
```

The problem seems to be when the zip command is rendered it is supplying 4 files. Two with the long temporary paths and two with the base paths.  It seems like the array return in the javascript expression in `valueFrom` is being appended to the original input value.

```
$ cwltool zip-files.cwl params.yaml
/Library/Frameworks/Python.framework/Versions/2.7/bin/cwltool 1.0.20170224141733
Resolved 'zip-files.cwl' to 'file:///Users/gmetzker/cwl-playground/zip-files/zip-files.cwl'
[job zip-files.cwl] /private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBTqPdM$ zip \
    myzip.zip \
    hello.txt \
    bye.txt \
    /private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBWzng6/stg0deafc0c-c165-45ae-ae10-054a20b5a91a/hello.txt \
    /private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBWzng6/stg88d3ead1-a6de-4c61-b5a2-168bed4b910f/bye.txt
  adding: hello.txt (stored 0%)
  adding: bye.txt (stored 0%)
  adding: private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBWzng6/stg0deafc0c-c165-45ae-ae10-054a20b5a91a/hello.txt (stored 0%)
  adding: private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBWzng6/stg88d3ead1-a6de-4c61-b5a2-168bed4b910f/bye.txt (stored 0%)
[job zip-files.cwl] completed success
{

    "zipFile": {
        "checksum": "sha1$4a137c63007d39c830d2a4491cdf7f864d4c6f36",
        "basename": "myzip.zip",
        "location": "file:///Users/gmetzker/cwl-playground/zip-files/myzip.zip",
        "path": "/Users/gmetzker/cwl-playground/zip-files/myzip.zip",
        "class": "File",
        "size": 1092
    }
}
Final process status is success
```

And here is the resulting zip file.  You can see the two extra files with the long paths.
```
$ unzip -vl myzip.zip
Archive:  myzip.zip

 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
      17  Stored       17   0%  03-09-17 16:09  354e5501  hello.txt
      18  Stored       18   0%  03-09-17 16:11  84bd4c1f  bye.txt
      17  Stored       17   0%  03-09-17 16:09  354e5501  private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBWzng6/stg0deafc0c-c165-45a
e-ae10-054a20b5a91a/hello.txt
      18  Stored       18   0%  03-09-17 16:11  84bd4c1f  private/var/folders/9h/j5_q_5hx4511j4blrvs9vc6c0000gq/T/tmpBWzng6/stg88d3ead1-a6de-4c6
1-b5a2-168bed4b910f/bye.txt
--------          -------  ---                            -------
      70               70   0%                            4 files
```

Is this a bug or am I doing something wrong? 

Sample files:
[zip-test.zip](https://github.com/common-workflow-language/cwltool/files/832915/zip-test.zip)

**Comment by mr-c** [comment]
Hello @gmetzker 

Thank you for your detailed report, I really appreciate it.

I have good news, soon `cwltool`'s treatment of inputs placed into the current working directory will  match the spec and you won't need to iterate over the array yourself: https://github.com/common-workflow-language/common-workflow-language/issues/405

You are probably still curious as to what is happening in your example above. Arrays can have multiple levels of `inputBinding`: one at the per item level, and for the overall array. Your example defines an `inputBinding` for the overall array and `cwltool` is supplying the default `inputBinding` behavior by (erroneously) including the non-current-working-directory path for each item.

Here is how to deploy your workaround until `cwltool` is brought into fuller compliance with the CWL v1.0 spec:

``` yaml
  srcFiles:
    inputBinding:
      position: 2
    type:
      type: array
      items: File
      inputBinding:
        valueFrom: $(self.basename)
```
Here I've had to use the expanded `array` syntax so that the per-item `inputBinding` can be used.

Since we already have an issue (#325) documenting `cwltool`'s need to better conform to the spec in this regard (thus eliminating the need for this workaround) I am going to close this issue. Feel free to report any other problems you have either here or by posting to https://www.biostars.org/t/cwl using the `cwl` tag.
