### ISSUE TITLE
Cwltool doesn't recognise syntax sugar for array of arrays

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/cwltool#330]
Example tool:

```yaml
cwlVersion: v1.0
requirements:
  ScatterFeatureRequirement: {}
class: Workflow
steps:
  add:
    run: add.cwl
    in:
      one: one
      two: two
    out: [sum]
    scatter: [one, two]
    scatterMethod: nested_crossproduct
inputs:
    one: int[]
    two: int[]
outputs:
    sum:
      outputSource: add/sum
      type: int[][]
```

Gives error:

    Field `type` references unknown identifier `int[][]`

**Comment by StarvingMarvin** [comment]
Bonus issue, this also fails:

```yaml
type:
    type: array
    items: int[]
```
