### ISSUE TITLE
specifying float or int inputs on command line to cwltool doesn't work

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#342]
- [ ] fix it
- [ ] add a test

make-instructions.cwl
``` yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

inputs:
  numbers:
    type: int[]
    inputBinding:
      itemSeparator: "+"

baseCommand: [ echo ]

outputs:
 response: stdout
```
```
(env) michael@dan:~/workshop$ cwltool make-instructions.cwl  --numbers 1
/home/michael/workshop/env/bin/cwltool 1.0.20170309164828
Resolved 'make-instructions.cwl' to 'file:///home/michael/workshop/make-instructions.cwl'
invalid field `job_order`, expected one of: 'numbers'
Workflow error, try again with --debug for more information:
Invalid job input record:
the `numbers` field is not valid because
  item is invalid because
    `'1'` is not int
```
