### ISSUE TITLE
Missing Basename when using current directory as an input

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/cwltool#376]
Hi all!
If use current directory as an input, cwltool fails to set a basename for this folder:
`WorkflowException: Invalid filename: '' contains illegal characters`
If add basename manually to the input in job file, all works

cwltool version 1.0.20170413194156

tool.cwl
```
cwlVersion: v1.0
class: CommandLineTool
hints:
- class: DockerRequirement
  dockerPull: ubuntu:latest
inputs:
  control_dir:
    type: Directory
outputs: []
baseCommand: [echo, 'hello']
```
job_fail.json
```
{
  "control_dir": {"class": "Directory", "location": "."}
}
```
job_success.json
```
{
  "control_dir": {"class": "Directory", "location": ".", "basename":"any"}
}
```
