### ISSUE TITLE
Wrong rdfs namespace in cwltool --print-rdf

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwltool#427]
## Expected Behavior

cwltool --print-rdf should use conventional valid namespaces where they exist.

## Actual Behavior

Wrong prefix for the `rdfs` namespace, seems to be caused by `<rdfs:comment>` being interpreted as an URI instead of a qname mapped to the rdfs namespace `http://www.w3.org/2000/01/rdf-schema# `

```turtle
@prefix ns1: <rdfs:> .
```

## Workflow Code

https://rawgit.com/common-workflow-language/workflows/master/workflows/hello/hello.cwl

## Full Traceback

     cwltool --print-rdf  https://rawgit.com/common-workflow-language/workflows/master/workflows/hello/hello.cwl

```turtle
@prefix SoftwareRequirement: <https://w3id.org/cwl/cwl#SoftwareRequirement/> .
@prefix Workflow: <https://w3id.org/cwl/cwl#Workflow/> .
@prefix cwl: <https://w3id.org/cwl/cwl#> .
@prefix ns1: <rdfs:> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
..
<https://rawgit.com/common-workflow-language/workflows/master/workflows/hello/hello.cwl#step0/62398b9b-8399-4f05-87e7-7abc669d9c0d/message> cwl:default "Hello World" ;
    cwl:inputBinding [ CommandLineBinding:position 1 ],
        [ CommandLineBinding:position 1 ] ;
    sld:type xsd:string ;
    ns1:comment "The message to print" .
```

## Your Environment
* cwltool version: 1.0.20170525215327

**Comment by stain** [comment]
Could it be because `Process.yml` etc uses:

```yaml
- name: SchemaBase
  type: record
  abstract: true
  fields:
    - name: label
      type:
        - "null"
        - string
      jsonldPredicate: "rdfs:label"
      doc: "A short, human-readable label of this object."
```

yet does not declare `rdfs` as a namespace?

```yaml
$namespaces:
  cwl: "https://w3id.org/cwl/cwl#"
  sld: "https://w3id.org/cwl/salad#"
```
