### ISSUE TITLE
Behaviour when both workflow's step and its tool define a default value for an input

### ISSUE THREAD

**Issue by undu** [common-workflow-language/cwltool#530]
In the case where both a workflow defines a default value and the tool in the step also defines one, cwltool picks the default value in the tool.

I haven't seen this behaviour been defined anywhere, and I would expect the values in the tool to be overridden since this is the only way I've seen to 'hardcode' values in workflows, but I don't know if that makes sense for everybody.

For example:
workflow.cwl
```
[...]
steps:
  step:
    run: tool.cwl
    in:
      parameter:
        default: 'workflow'
[...]
```

```
[...]
baseCommand: echo
inputs:
  parameter:
    type: string
    default: tool
```

This would print `tool`, I'd expect it to print `workflow`.

Is this something expected? I can produce conformity tests and tests for cwltool if necessary.
