### ISSUE TITLE
Feature request: remote file access

### ISSUE THREAD

**Issue by AleksandrSl** [common-workflow-language/cwltool#539]
Do you have any plans to add remote File access, e.g. through http(s) or from S3 storage?

**Comment by tetron** [comment]
A http download feature was merged in 1.0.20170810192106 although I haven't used it, so I am interested to hear if it meets your needs or not.

**Comment by Welliton309** [comment]
I tested this feature and it is working (version `1.0.20170828135420`).
Here is a simple working example.

Workflow:

``` yml
cwlVersion: v1.0
class: Workflow

requirements:
  ScatterFeatureRequirement: {}
  StepInputExpressionRequirement: {}

inputs:
  files: File[]
  workers: int
  groups: string[]

outputs:
  qa_report_raw:
    type: File
    outputSource: qa_raw/qc_report

steps:
  qa_raw:
    run: https://raw.githubusercontent.com/labbcb/docker-rqc/master/Rqc.cwl
    in:
      files: files
      groups: groups
      workers: workers
    out: [qc_report]
```

Input:

``` yml
files: 
  - class: File
    path: "https://github.com/Bioconductor-mirror/ShortRead/raw/release-3.5/inst/extdata/E-MTAB-1147/ERR127302_1_subset.fastq.gz"
  - class: File
    path: "https://github.com/Bioconductor-mirror/ShortRead/raw/release-3.5/inst/extdata/E-MTAB-1147/ERR127302_2_subset.fastq.gz"

workers: 2
groups: [None, None]
```
