### ISSUE TITLE
'format' key in input YAML interpreted as file

### ISSUE THREAD

**Issue by esanzgar** [common-workflow-language/cwltool#568]
When the input file is a YAML that contains a key named 'format', then it is interpreted as file.

Workflow, echo.cwl:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo

inputs:
  format:
    type: string
    inputBinding:
      position: 1

outputs:
    output: stdout
```

Input YAML, hello_world.yaml:
```
format: Hello world
```

Usage:
```
cwltool echo.cwl hello_world.yaml
```

## Expected Behavior
The output file should contain the string: 'Hello world'.
Similar to cwltool echo.cwl --format 'Hello world'

## Actual Behavior
Output file contains a path to a file: file:///path/to/working/directory/Hello world

## Workflow Code
```
Paste the template code (ideally a minimal example) that causes the issue

```

## Your Environment
* cwltool version: 1.0.20170928192020
