### ISSUE TITLE
nested anonymous directories fail

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#578]
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing:
      - class: Directory
        basename: x
        listing:
          - class: Directory
            basename: y
            listing: []

inputs: []

stdout: tree.txt

outputs:
  listing: stdout

baseCommand: find
```
```
/home/michael/cwltool/env/bin/cwltool 1.0.20171107133715
Resolved 'dir-creation.cwl' to 'file:///home/michael/cwltool/dir-creation.cwl'
Parsed job order from command line: {
    "id": "dir-creation.cwl"
}
[job dir-creation.cwl] initializing from file:///home/michael/cwltool/dir-creation.cwl
[job dir-creation.cwl] {}
[job dir-creation.cwl] path mappings is {}
[job dir-creation.cwl] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "datum": "find"
    }
]
[job dir-creation.cwl] initial work dir {
    "_:bf9f1988-aaf4-444b-a6ca-0d6dd2db21b4": [
        "_:bf9f1988-aaf4-444b-a6ca-0d6dd2db21b4", 
        "/tmp/tmpsyc_95/x", 
        "Directory", 
        true
    ], 
    "_:89e99889-6ddf-4d19-87d7-8b1535598f8d": [
        "_:89e99889-6ddf-4d19-87d7-8b1535598f8d", 
        "/tmp/tmpsyc_95/x/y", 
        "Directory", 
        true
    ]
}
Got workflow error
Traceback (most recent call last):
  File "/home/michael/cwltool/env/local/lib/python2.7/site-packages/cwltool/main.py", line 290, in single_job_executor
    r.run(**kwargs)
  File "/home/michael/cwltool/env/local/lib/python2.7/site-packages/cwltool/job.py", line 308, in run
    relink_initialworkdir(self.generatemapper, self.outdir, self.builder.outdir, inplace_update=self.inplace_update)
  File "/home/michael/cwltool/env/local/lib/python2.7/site-packages/cwltool/job.py", line 120, in relink_initialworkdir
    os.symlink(vol.resolved, host_outdir_tgt)
OSError: [Errno 2] No such file or directory
Workflow error, try again with --debug for more information:
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/michael/cwltool/env/local/lib/python2.7/site-packages/cwltool/main.py", line 917, in main
    **vars(args))
  File "/home/michael/cwltool/env/local/lib/python2.7/site-packages/cwltool/main.py", line 298, in single_job_executor
    raise WorkflowException(Text(e))
WorkflowException: [Errno 2] No such file or directory
```
