### ISSUE TITLE
Cannot make job: Workflow contains multiple inbound links to a single parameter but MultipleInputFeatureRequirement is not declared.

### ISSUE THREAD

**Issue by dyermd** [common-workflow-language/cwltool#579]
## Expected Behavior
I have a simple workflow consisting of two steps. Each of the two steps executes just find by themselves and when I run `rabbix-cli` on the workflow it also works fine. The workflow and modules are defined in CWL v1.0 so I would expect the workflow to also run fine when using `cwltool`.

## Actual Behavior
When I execute the workflow, I get the following error.

```
[workflow genome-resequencing.cwl] start
[step sam2bam] Cannot make job: Workflow contains multiple inbound links to a single parameter but MultipleInputFeatureRequirement is not declared.
[workflow genome-resequencing.cwl] Cannot collect workflow output: Workflow contains multiple inbound links to a single parameter but MultipleInputFeatureRequirement is not declared.
[workflow genome-resequencing.cwl] completed permanentFail
```

## Workflow Code
```
class: Workflow
cwlVersion: v1.0
id: genome_resequencing
label: genome-resequencing
inputs:
  - id: reference
    type: File
    'sbg:x': -1317.8768310546875
    'sbg:y': -575.5
  - id: fastq
    type: File
    'sbg:x': -1319.8768310546875
    'sbg:y': -408.5
outputs:
  - id: bam
    outputSource:
      - sam2bam/bam
    type: File
    'sbg:x': -627.2568359375
    'sbg:y': -507
steps:
  - id: graphmap
    in:
      - id: fastq
        source:
          - fastq
      - id: reference
        source:
          - reference
    out:
      - id: sam
      - id: graphmap_results
    run: >-
      graphmap.cwl
    label: graphmap
    'sbg:x': -1058.8768310546875
    'sbg:y': -494.5
  - id: sam2bam
    in:
      - id: sam
        source:
          - graphmap/sam
    out:
      - id: bam
      - id: sam2bam_results
      - id: bam_index
    run: >-
      sam2bam.cwl
    label: sam2bam
    'sbg:x': -860.8768310546875
    'sbg:y': -499.5

```

graphmap.cwl

```
class: CommandLineTool
cwlVersion: v1.0
id: graphmap
baseCommand:
  - python
  - /usr/src/app/graphmap.py
inputs:
  - id: fastq
    type: File
    inputBinding:
      position: 0
      prefix: '-f'
    label: FASTQ
  - id: reference
    type: File
    inputBinding:
      position: 0
      prefix: '-r'
    label: Reference FASTA
    secondaryFiles:
      - .gmidx
outputs:
  - id: sam
    label: SAM
    type: File
    outputBinding:
      glob: '*.sam'
  - id: graphmap_results
    label: Results JSON
    type: File
    outputBinding:
      glob: '*results.json'
label: graphmap
arguments:
  - position: 0
    prefix: '-c'
    valueFrom: runtime.cores
requirements:
  - class: ResourceRequirement
    ramMin: 1000
    coresMin: 1
  - class: DockerRequirement
    dockerPull: 'dnadocker/graphmap:1.0.5'
'sbg:job':
  inputs:
    fastq:
      basename: reads.fastq
      class: File
      contents: file contents
      nameext: .fastq
      nameroot: f
      path: reads.fastq
      secondaryFiles: []
      size: 0
    reference:
      basename: reference.fasta
      class: File
      contents: file contents
      nameext: .fasta
      nameroot: reference
      path: reference.fasta
      secondaryFiles: []
      size: 0
  runtime:
    cores: 1
    ram: 1000
```

sam2bam.cwl

```
class: CommandLineTool
cwlVersion: v1.0
id: sam2bam
baseCommand:
  - python
  - /usr/src/app/sam2bam.py
inputs:
  - id: sam
    type: File
    inputBinding:
      position: 0
      prefix: '-s'
    label: SAM
outputs:
  - id: bam
    label: BAM
    type: File
    outputBinding:
      glob: '*.bam'
  - id: sam2bam_results
    label: Results JSON
    type: File
    outputBinding:
      glob: '*results.json'
  - id: bam_index
    label: BAM Index
    type: File
    outputBinding:
      glob: '*.bam.bai'
label: sam2bam
requirements:
  - class: ResourceRequirement
    ramMin: 1000
    coresMin: 1
  - class: DockerRequirement
    dockerPull: 'dnadocker/sam2bam:1.0.5'
'sbg:job':
  inputs:
    sam:
      basename: reads.sam
      class: File
      contents: file contents
      nameext: .ext
      nameroot: input
      path: reads.sam
      secondaryFiles: []
      size: 0
  runtime:
    cores: 1
    ram: 1000
```

## Full Traceback
```pytb
modules/graphmap.cwl:45:3:   checking field `inputs`
modules/graphmap.cwl:46:5:     checking object `modules/graphmap.cwl#fastq`
modules/graphmap.cwl:52:7:       Field `path` contains undefined reference to `file:///reads.fastq`
modules/graphmap.cwl:55:5:     checking object `modules/graphmap.cwl#reference`
modules/graphmap.cwl:61:7:       Field `path` contains undefined reference to `file://reference.fasta`
modules/graphmap.cwl:44:1: unrecognized extension field `sbg:job`.  Did you include a $schemas section?
modules/sam2bam.cwl:38:3:   checking field `inputs`
modules/sam2bam.cwl:39:5:     checking object `modules/sam2bam.cwl#sam`
modules/sam2bam.cwl:45:7:       Field `path` contains undefined reference to `file:///reads.sam`
modules/sam2bam.cwl:37:1: unrecognized extension field `sbg:job`.  Did you include a $schemas section?
Parsed job order from command line: {
    "fastq": {
        "class": "File", 
        "location": "file:///ecoli_small.fastq"
    }, 
    "id": "genome-resequencing.cwl", 
    "reference": {
        "class": "File", 
        "location": "file:///ecoli_k12.fasta"
    }
}
[workflow genome-resequencing.cwl] initialized from file:///genome-resequencing.cwl
[workflow genome-resequencing.cwl] start
[step graphmap] Cannot make job: Workflow contains multiple inbound links to a single parameter but MultipleInputFeatureRequirement is not declared.

Traceback (most recent call last):
  File "/Users/mattdyer/Documents/Programming/venv/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 484, in job
    for newjob in step.iterable:
  File "/Users/mattdyer/Documents/Programming/venv/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 352, in try_make_job
    self.state, inputparms, False, supportsMultipleInput, "source")
  File "/Users/mattdyer/Documents/Programming/venv/cwl/lib/python2.7/site-packages/cwltool/workflow.py", line 212, in object_from_state
    "Workflow contains multiple inbound links to a single "
WorkflowException: Workflow contains multiple inbound links to a single parameter but MultipleInputFeatureRequirement is not declared.
[workflow genome-resequencing.cwl] Cannot collect workflow output: Workflow contains multiple inbound links to a single parameter but MultipleInputFeatureRequirement is not declared.
[workflow genome-resequencing.cwl] completed permanentFail
Removing intermediate output directory /var/folders/nf/2z_q4wb52l3cyf0631xbtyzh0000gn/T/tmpvqYlSf

```

## Your Environment
* cwltool version:  1.0.20171107133715
