### ISSUE TITLE
Workflow defaults do not override CommandLineTool defaults

### ISSUE THREAD

**Issue by kellrott** [common-workflow-language/cwltool#592]
## Expected Behavior
Default values defined at the workflow level would override default values provided in the CommandLineTool

## Actual Behavior
Workflow level default values are ignored and CommandLineTool defaults are used

## Workflow Code
test_wf.cwl:
```
cwlVersion: v1.0
class: Workflow

inputs: []
  
steps:
  echo:
    run: test_tool.cwl
    in:
      phrase: 
        default: planet
    out: 
      - output

outputs:
  output:
    type: File
    outputSource: echo/output
```

test_tool.cwl:
```

cwlVersion: v1.0
class: CommandLineTool

baseCommand: [ echo ]

inputs:
  phrase:
    type: string
    default: "world"
    inputBinding:
      position: 1

stdout: out.file

outputs:
  output: 
    type: File
    outputBinding:
      glob: out.file
```

## Full Traceback
```
# cwltool test_wf.cwl
# cat out.file
world
```
expected cat.outfile would be `planet`

## Your Environment
* cwltool version: 
`1.0.20171227212058`
