### ISSUE TITLE
Parameter with a valueFrom field, type array and no prefix doesn't lead to execution of the expected command

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#593]
If you use the valueFrom field with an argument of array type and no prefix field, the executed command is the evaluated valueFrom field followed by the array arguments, not just the  evaluated valueFrom field. This is not what I would expect from the cwl specification and behaviour of cwltool.

## Expected Behaviour

From http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineBinding:
> If valueFrom is a constant string value, use this as the value and apply the binding rules above.

It is not specified in the specification what the binding rules should be if no prefix is defined, but in cwltool if no `prefix` field is present, then cwltool doesn't evaulate the anything for that argument e.g.:
```yaml
cwlVersion: v1.0
inputs:
  - id: parameter
    type:
      - type: array
        items: string
outputs: []
class: CommandLineTool
baseCommand: echo
```
```yaml
parameter:
  - "item1"
  - "item2"
```

Outputs:
```
/usr/local/bin/cwltool 1.0.20171107133715
Resolved 'test.cwl' to '...'
[job test.cwl] /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp1mivk5pg$ echo

[job test.cwl] completed success
{}
Final process status is success
```
I would therefore infer that using the workflow and inputs below should execute ` 'echo' 'replacementValue'`, but cwltool executes: `'echo' 'replacementValue' 'item1' 'item2'`.
## Actual Behaviour
Using the workflow and inputs below, cwltool outputs as specified below:

### Workflow
```yaml
cwlVersion: v1.0
requirements:
- class: ShellCommandRequirement
- class: InlineJavascriptRequirement
inputs:
  - id: parameter
    type:
      - type: array
        items: string
    inputBinding:
      valueFrom: replacementValue
outputs: []
class: CommandLineTool
baseCommand: echo
```
### Inputs
```yaml
parameter:
  - "item1"
  - "item2"
```

## Full Traceback
```pytb
/usr/local/bin/cwltool 1.0.20171107133715
Resolved 'test.cwl' to '...'
[job test.cwl] /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp_jdgzuc4$ /bin/sh \
    -c \
    'echo' 'replacementValue' 'item1' 'item2'
replacementValue item1 item2
[job intervals_test.cwl] completed success
{}
Final process status is success
```

## Your Environment
* cwltool version: 1.0.20171107133715
