### ISSUE TITLE
cwltool --validate should validate that javascript expressions are valid ES5 expressions

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#594]
It would be nice if `cwltool --validate` would report ES5 syntax errors in cwl expressions e.g. running `cwltool --validate` with this:
```yaml
cwlVersion: v1.0
requirements:
- class: InlineJavascriptRequirement
inputs:
  - id: parameter
    type: string
    inputBinding:
      valueFrom: $((_ => "test")())
outputs: []
class: CommandLineTool
baseCommand: echo
```
would report an error, as it uses ES6 syntax.
