### ISSUE TITLE
Float values not being recognized?

### ISSUE THREAD

**Issue by jorvis** [common-workflow-language/cwltool#61]
In my CWL I have:

```
  - id: evalue
    type: ["null", float]
    inputBinding:
      position: 4
      prefix: -evalue
      separate: true
```

And then in my test JSON file for it I've tried both:

`    "evalue": 2e-10,`

and

`    "evalue": "2e-10",`

But when I run I get:

```
/usr/local/bin/cwl-runner 1.0.20160331184641
Workflow error, try again with --debug for more information:
  Error validating input record, could not validate field `evalue` because
  the value `'2e-10'` is not a valid type in the union, expected one of:
  - null, but
     the value `'2e-10'` is not null
  - float, but
     the value `'2e-10'` is not float or double


[blast+-blastp.cwl.txt](https://github.com/common-workflow-language/cwltool/files/208737/blast.-blastp.cwl.txt)
[blast+-blastp.test.json.txt](https://github.com/common-workflow-language/cwltool/files/208736/blast.-blastp.test.json.txt)

```
