### ISSUE TITLE
Unable to omit 'Unrecognized extension field' warnings for fields in RDF schema

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/cwltool#623]
Hi,
The attachment contains test files to reproduce the issue (CWL and the xml schema file) - [cwl-schemas.tar.gz](https://github.com/common-workflow-language/common-workflow-language/files/1660407/cwl-schemas.tar.gz)

When running the tool with cwltool version 1.0.20180116213856 an 'Unrecognized extension field' warning is printed out. While running with an older version (1.0.20170413194156) there was no warning.
`cwltool schemas-tool1.cwl -- --input foobar`

## Expected Behavior
After including $schemas in the CWL, cwltool should not print out a warning.

## Actual Behavior
After including $schemas in the CWL, cwltool version 1.0.20180116213856 prints out a warning.

## Workflow Code
```
class: CommandLineTool
cwlVersion: v1.0
id: schema
baseCommand:
  - echo
inputs:
  - id: input
    type: string?
    inputBinding:
      position: 0
outputs:
  - id: output
    type: File?
    outputBinding:
      glob: stdout.txt
label: schemas-tool1
requirements:
  - class: DockerRequirement
    dockerPull: 'ubuntu:16.04'
stdout: stdout.txt
$namespaces:
  sbg: 'http://sbgenomics.com/schema#'
$schemas:
  - sbg-schema.xml
'sbg:appVersion':
  - v1.0
```

## Full Traceback
```pytb
schemas-tool1.cwl:1:1: unrecognized extension field `http://sbgenomics.com/schema#appVersion`.  Did you include a $schemas section?
```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``

**Comment by tetron** [comment]
Hmm, this looks correct, will have to investigate.

**Comment by tetron** [comment]
Also, this is actually a schema-salad bug.  You should get a similar result using schema-salad-tool for validation:

```
schema-salad-tool common-workflow-language/v1.0/CommonWorkflowLanguage.yml schemas-tool1.cwl
```

**Comment by bogdang989** [comment]
Cool, thanks for the quick response.

**Comment by bogdang989** [comment]
Yes, actually when running with schema-salad-tool version 2.6.20171201034858 there is no warning

**Comment by tetron** [comment]
Perhaps you just need to update the version of schema salad you are using with cwltool?

**Comment by anton-khodak** [comment]
Confirming with cwltool 1.0.20180116213856, using schema-salad of the latest version does not help

**Comment by keiranmraine** [comment]
also #455 (discussed with mr-c on gitter 14-Dec)

**Comment by tetron** [comment]
This turn out to be a really stupid bug.  The default for --skip-schemas is True so it would _never_ load the schemas as intended. See #656 has the fix.

Separately there is a schema-salad bug that it prints warnings even when extension schemas were skipped.

**Comment by mr-c** [comment]
@tetron I can confirm that the behaviour of `--skip-schemas` is fixed, however `cwltool` is still printing a false warning:
`test.cwl:1:1: unrecognized extension field 'http://edamontology.org/topic_0003'.  Did you include a $schemas section?`

Here's a minimal reproducible version:
```
class: CommandLineTool
cwlVersion: v1.0
id: schema
baseCommand: [] 
inputs:
  first:
    type: File
    format: edam:format_1930  # FASTQ
outputs: []


$namespaces:
  edam: http://edamontology.org/

$schemas:
  http://edamontology.org/EDAM_1.16.owl

edam:topic_0003: edam:topic_3500

```
