### ISSUE TITLE
Any[] is incompatible with any array type apart from Any[]

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#638]
With the workflow:
```
cwlVersion: v1.0
class: Workflow

inputs:
  input:
    type: Any[]

steps: []

outputs:
  - id: output
    type: string[]
    outputSource: input
```
`cwltool --validate` reports the error:
```
/usr/local/bin/cwltool 1.0.20180130110340
Resolved 'workflows/test_workflow.cwl' to 'file:///Users/th10/checkouts/arvados-pipeline/arvados-pipelines/cwl/workflows/test_workflow.cwl'
Tool definition failed validation:
workflows/test_workflow.cwl:6:5: Source 'input' of type {"type": "array", "items": "Any"} is incompatible
workflows/test_workflow.cwl:12:5:   with sink 'output' of type {"type": "array", "items": "string"}
```

Any is supposed to be compatible with any other type, so Any[] should be compatible with any other array type - this is not the case.

## Your Environment
* cwltool version: 1.0.20180130110340
