### ISSUE TITLE
Second expression in concatenated valueFrom is ignored

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#643]
In the CommandLineTool:
```yaml
cwlVersion: v1.0
requirements:
  - class: InlineJavascriptRequirement
inputs:
  - id: parameter
    inputBinding:
      valueFrom: $("a ")$("string")
    type: string?
outputs: []
class: CommandLineTool
baseCommand: echo
```

The expression `$("a ")` is ignored on when this is run:

```
/usr/local/bin/cwltool 1.0.20180130110340
Resolved 'test.cwl' to 'file:///Users/th10/checkouts/arvados-pipeline/arvados-pipelines/cwl/test.cwl'
[job test.cwl] /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmp8fqrl6ng$ echo \
    string
string
[job test.cwl] completed success
{}
Final process status is success
```

CWL version: 1.0.20180130110340
