### ISSUE TITLE
Bad level of secondaryFiles in outputs doesn't throw an error

### ISSUE THREAD

**Issue by keiranmraine** [common-workflow-language/cwltool#645]
## Expected Behavior

When an output (possibly other areas to) binding has secondarFiles defined at the wrong level an error should be thrown.

## Actual Behavior

When indented too far secondaryFiles is not interpreted and no validation errors are raised

```
outputs:
  out_cram:
    type: File
    outputBinding:
      glob: $(inputs.sample).cram
      secondaryFiles:
      - .crai
```

cwltool happily processes but the `.crai` file is not captured.

## Workflow Code
```
Paste the template code (ideally a minimal example) that causes the issue

```

## Full Traceback

no error is raised bad config results in stdout of:

```
{
    "out_bam": {
        "checksum": "sha1$e9e4c479937e797baf0f570b71bff0fd6de71138", 
        "basename": "test.bam", 
        "location": "file:///home/ubuntu/datastore/launcher-4ba554fc-47d6-472d-b1c6-26955e8f600c/outputs/test.bam", 
        "path": "/home/ubuntu/datastore/launcher-4ba554fc-47d6-472d-b1c6-26955e8f600c/outputs/test.bam", 
        "class": "File", 
        "size": 6600410
    }
}
```

## Your Environment

```
/usr/local/bin/cwltool 1.0.20170828135420
```
