### ISSUE TITLE
Regression in handling enum type option

### ISSUE THREAD

**Issue by partha-edico** [common-workflow-language/cwltool#704]
## Expected Behavior
cwltool should handle an input type such as the following:
    type:
    - 'null'
    - type: enum
      symbols: ['across', 'commas','long']

## Actual Behavior
As of release 1.0.20180322194411 (NOTE: Previous release 1.0.20180306163216 worked OK), we get cwltool parsing errors:
=> cwl_test.yaml:13:7: invalid field `name`, expected one of: 'symbols', 'type', 'label', 'inputBinding'

### cwl_tool.yaml
```
baseCommand: /bin/ls
class: CommandLineTool
cwlVersion: v1.0
hints: []
requirements:
- {class: InlineJavascriptRequirement}
inputs:
  ls_format:
    type:
    - 'null'
    - type: enum
      symbols: ['across','commas','long']
    label: Format type
    inputBinding: {position: 3, prefix: --format, itemSeparator: '='}
outputs:
  bam_output:
    type: File?
    outputBinding: {glob: '*.bam'}
stderr: stderr.txt
stdout: stdout.txt
```
### test_input.yaml
```
ls_format: 'long'
```

## Full Traceback
No exception

## Your Environment
* cwltool version: 1.0.20180322194411
