### ISSUE TITLE
Unexpected Behaviour renaming nested workflow as the step name

### ISSUE THREAD

**Issue by FarahZKhan** [common-workflow-language/cwltool#720]
I am running the dummy [nested workflow example](http://www.commonwl.org/user_guide/22-nested-workflows/) from the user guide which is running the [1st workflow example](http://www.commonwl.org/user_guide/21-1st-workflow/) as nested workflow.

## Expected Behavior
The nested workflow should have be referred by its name in the logged info:
```
[workflow nested-workflow.cwl] starting step compile
[step compile] start
[workflow 1st-workflow.cwl] start
[workflow 1st-workflow.cwl] starting step untar
[step untar] start
```

## Actual Behavior
The outer step name is used as nested workflow name:
```
[workflow nested-workflow.cwl] starting step compile
[step compile] start
[workflow compile] start
[workflow compile] starting step untar
[step untar] start
```

## Workflow Code
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

inputs: []

outputs:
  classout:
    type: File
    outputSource: compile/classout

requirements:
  - class: SubworkflowFeatureRequirement

steps:
  compile:
    run: 1st-workflow.cwl
    in:
      inp:
        source: create-tar/tar
      ex:
        default: "Hello.java"
    out: [classout]

  create-tar:
    requirements:
      - class: InitialWorkDirRequirement
        listing:
          - entryname: Hello.java
            entry: |
              public class Hello {
                public static void main(String[] argv) {
                    System.out.println("Hello from Java");
                }
              }
    in: []
    out: [tar]
    run:
      class: CommandLineTool
      requirements:
        - class: ShellCommandRequirement
      arguments:
        - shellQuote: false
          valueFrom: |
            date
            tar cf hello.tar Hello.java
            date
      inputs: []
      outputs:
        tar:
          type: File
          outputBinding:
            glob: "hello.tar"

```
## Your Environment
* cwltool version: 1.0.20180403145700
