### ISSUE TITLE
"Missing required secondary file" for workflow execution 

### ISSUE THREAD

**Issue by yuankunzhu** [common-workflow-language/cwltool#725]
---

## Expected Behavior
input secondaryFiles doesn't have to be declared again at the workflow level

## Actual Behavior
the latest release [1.0.20180403145700](https://github.com/common-workflow-language/cwltool/tree/1.0.20180403145700) will fail and error out like: "Cannot make job: Missing required secondary file", even when the secondaryFiles has already been declared on the CommandLineTool level. all previous release works fine with such cases. 

### 1. tool.cwl
```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  - class: ShellCommandRequirement
baseCommand: []
arguments:
  - position: 0
    shellQuote: false
    valueFrom: echo $(inputs.ref.path)
inputs:
  ref: { type: File, secondaryFiles: [.fai] }
outputs:
  output: stdout
```
run tool along
```
$ cwltool tool.cwl --ref /vol/dev/broad-references/Homo_sapiens_assembly38.fasta
/vol/venv/workflow-dev/bin/cwltool 1.0.20180326152342
Resolved 'tool.cwl' to 'file:///vol/dev/yuankun/debug-new-workflow/new/workflows/tool.cwl'
[job tool.cwl] /tmp/tmp4UfUEW$ /bin/sh \
    -c \
    echo /tmp/tmpEkJep_/stg19fcc510-80fe-4446-9ea8-96964f40edc9/Homo_sapiens_assembly38.fasta > /tmp/tmp4UfUEW/0dfb339b948eaf6673c1089f8364172c01340b6b
[job tool.cwl] completed success
{
    "output": {
        "checksum": "sha1$ac141583df098eef28e77b14a59571c8eaec24e9",
        "basename": "0dfb339b948eaf6673c1089f8364172c01340b6b",
        "location": "file:///vol/dev/yuankun/debug-new-workflow/new/workflows/0dfb339b948eaf6673c1089f8364172c01340b6b",
        "path": "/vol/dev/yuankun/debug-new-workflow/new/workflows/0dfb339b948eaf6673c1089f8364172c01340b6b",
        "class": "File",
        "size": 85
    }
}
Final process status is success
```
### 2. workflow
```
cwlVersion: v1.0
class: Workflow
inputs:
  ref: File
outputs: []
steps:
  tool:
    run: tool.cwl
    in:
      ref: ref
    out: [output]
```
2.1 run workflow with [1.0.20180326152342](https://github.com/common-workflow-language/cwltool/tree/1.0.20180326152342)
```
$ cwltool workflow.cwl --ref /vol/dev/broad-references/Homo_sapiens_assembly38.fasta
/vol/venv/workflow-dev/bin/cwltool 1.0.20180326152342
Resolved 'workflow.cwl' to 'file:///vol/dev/yuankun/debug-new-workflow/new/workflows/workflow.cwl'
[workflow workflow.cwl] start
[step tool] start
[job tool] /tmp/tmp3iNFjf$ /bin/sh \
    -c \
    echo /tmp/tmpl2R0AD/stg6a8eaa99-8407-4272-a03a-71c77b5cb57a/Homo_sapiens_assembly38.fasta > /tmp/tmp3iNFjf/0dfb339b948eaf6673c1089f8364172c01340b6b
[job tool] completed success
[step tool] completed success
[workflow workflow.cwl] completed success
```
2.2 run workflow with [1.0.20180403145700](https://github.com/common-workflow-language/cwltool/tree/1.0.20180403145700)
```
$ cwltool workflow.cwl --ref /vol/dev/broad-references/Homo_sapiens_assembly38.fasta
/vol/venv/workflow-dev/bin/cwltool 1.0.20180403145700
Resolved 'workflow.cwl' to 'file:///vol/dev/yuankun/debug-new-workflow/new/workflows/workflow.cwl'
[workflow workflow.cwl] start
[step tool] start
Exception on step 'tool'
[step tool] Cannot make job: Missing required secondary file 'Homo_sapiens_assembly38.fasta.fai' from file object: {
    "basename": "Homo_sapiens_assembly38.fasta",
    "nameroot": "Homo_sapiens_assembly38",
    "nameext": ".fasta",
    "location": "file:///vol/dev/broad-references/Homo_sapiens_assembly38.fasta",
    "secondaryFiles": [],
    "class": "File",
    "size": 3249912778
}
[workflow workflow.cwl] completed permanentFail
{}
Final process status is permanentFail
```
