### ISSUE TITLE
providing a string for an input with type File needs a better error message

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#758]
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  required_file: File
outputs:
  path: stdout
```

```
required_file: "not_a_file"
```

```
$ cwltool minimal.cwl null.yaml 
/home/mcrusoe/src/toil/venv/bin/cwltool 1.0.20180403145700
Resolved 'minimal.cwl' to 'file:///home/mcrusoe/common-workflow-language/v1.0/minimal.cwl'
Workflow error, try again with --debug for more information:
Invalid job input record:
null.yaml:1:1: the `required_file` field is not valid because
                 is not a dict
```

**Comment by golharam** [comment]
Is this still outstanding?  I'm running into this myself.

**Comment by tetron** [comment]
Probably.  There error is coming from generic validation which doesn't know anything about files, just that a file is an object and it expected an object and got a string instead.  Given this is a really common error it there should probably be some additional handling that gives a better error or even some an extra "do what I mean" fix-up.

**Comment by mr-c** [comment]
The work around to is specify the input as follows:

`inputs.yml`
``` yml

required_file:
  class: File
  path: relative_path/to/my_file   # or an absolute path
```
