### ISSUE TITLE
extraneous warning: optional input connected to step with required input that has a default value

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#759]
dynresreq-workflow-stepdefault.cwl:
```
#!/usr/bin/env cwl-runner
class: Workflow
cwlVersion: v1.0

inputs:
  special_file: File?
outputs:
  cores:
    type: File
    outputSource: report/output

steps:
  count:
    in:
      special_file:
        source: special_file
        default:
          class: File
          location: special_file
    out: [output]
    run: dynresreq.cwl

  report:
    in:
      file1: count/output
    out: [output]
    run: cat-tool.cwl
```
(the remaining files are from the CWL v1.0 repo)

```
/home/mcrusoe/src/toil/venv/bin/cwltool 1.0.20180508202931
Resolved 'v1.0/dynresreq-workflow.cwl' to 'file:///home/mcrusoe/common-workflow-language/v1.0/v1.0/dynresreq-workflow.cwl'
Workflow checker warning:
v1.0/dynresreq-workflow.cwl:6:3: Source 'special_file' of type ["null", "File"] may be incompatible
v1.0/dynresreq-workflow.cwl:15:7:   with sink 'special_file' of type "File"
```
