### ISSUE TITLE
Can double define variables without warning/error

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#773]
```
  make_skymodel:
    run: steps/skymodel.cwl
    in:
      nsrc: randomize/nsrc
      nsrc: nsrc

    out:
      [skymodel]
```
Not a huge problem but this has just has gone unnoticed in one of our pipelines for a long time, maybe good to make it invalid?
