### ISSUE TITLE
Output in subdirectory is moved to root

### ISSUE THREAD

**Issue by jirikuncar** [common-workflow-language/cwltool#774]
## Expected Behavior
Result should appear in `data` subdirectory.

## Actual Behavior
`1.wc` is copied to working directory.

## Workflow Code
```
arguments: []
baseCommand:
- wc
class: CommandLineTool
cwlVersion: v1.0
hints: []
inputs:
  input_stdin:
    default:
      class: File
      path: data/1.txt
    streamable: false
    type: File
outputs:
  output_stdout:
    streamable: false
    type: stdout
permanentFailCodes: []
requirements: []
stdin: $(inputs.input_stdin.path)
stdout: data/1.wc
successCodes: []
temporaryFailCodes: []
```

## Full log
```console
$ cwltool wc.cwl
/bin/cwltool 1.0.20180525185854
Resolved 'wc.cwl' to 'file:///.../wc.cwl'
[job wc.cwl] /private/tmp/docker_tmpgap9ihqh$ wc < /private/var/folders/l9/n7bykj252_xd_q78m7fpnh_r0000gn/T/tmp0gov7l2m/stgaef901f9-5c63-4ab5-908d-057035224f09/1.txt > /private/tmp/docker_tmpgap9ihqh/data/1.wc
[job wc.cwl] completed success
{
    "output_stdout": {
        "location": "file:///.../1.wc",
        "basename": "1.wc",
        "class": "File",
        "checksum": "sha1$21ed1bf783abb9147a12ad987f78120d92327ca3",
        "size": 25,
        "path": "/.../1.wc"
    }
}
Final process status is success
```

## Your Environment
* cwltool version: `1.0.20180525185854`
