### ISSUE TITLE
parsing error for a simple workflow

### ISSUE THREAD

**Issue by SooLee** [common-workflow-language/cwltool#78]
```
Hello I've tried a simple workflow but I got an error message and I couldn't find out what I did wrong. Could anyone help me with it? I'd appreciate it.
By the way, I checked the indentations are okay and I didn't use any tab instead of space.
Could it be a bug in the parser? Hope it's something easy I can fix. Thanks in advance.

-bash-4.1$ cat hello.workflow.cwl 
cwlVersion: cwl:draft-3
class: Workflow
inputs:
  - id: input_message
    type: string

outputs:
  - id: finaloutput
    type: File
    source: "#wc/outputfile"

steps:
  - id: hello2
    run: hello2.cwl
    inputs:
      - id: message
        source: "#input_message"
    outputs:
      - id: output

   - id: wc
     run: wc.cwl
     inputs:
       - id: inputfile
         source: "#hello2/output"
     outputs:
       - id: outputfile
 
-bash-4.1$ cat hello2.cwl 
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: echo
stdout: output.txt
inputs:
  - id: message
    type: string
    inputBinding:
      position: 1
outputs:
  - id: output
    type: File
    outputBinding:
      glob: output.txt

-bash-4.1$ cat wc.cwl 
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: wc
stdout: wc.output.txt
inputs:
  - id: inputfile
    type: File
    inputBinding:
      position: 1
outputs:
  - id: outputfile
    type: File
    outputBinding:
      glob: wc.output.txt

-bash-4.1$ cat hello.workflow-job1.yml 
input_message: Yay! Hello world!


-bash-4.1$ cwl-runner hello.workflow.cwl hello.workflow-job1.yml
/home/duplexa/venv/cwl/bin/cwl-runner 1.0.20160504183010
I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
Syntax error while parsing a block collection
  in "file:///home/duplexa/emsar.workflow/hello.workflow.cwl", line 13, column 3
expected <block end>, but found '<block sequence start>'
  in "file:///home/duplexa/emsar.workflow/hello.workflow.cwl", line 21, column 4

```
