### ISSUE TITLE
inconsistent behavior: passing file paths via command line arguments vs input job documents

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#79]
``` yaml
#!/usr/bin/env cwl-runner

cwlVersion: cwl:draft-3
class: CommandLineTool

baseCommand: wc

inputs:
  - id: inputfile
    type: File
    inputBinding:
      position: 1

outputs:
  - id: outputfile
    type: File
    outputBinding:
      glob: $((inputs.inputfile.path + '.wc').replace(runtime.outdir + '/', ''))

stdout: $(inputs.inputfile.path + '.wc')

requirements:
  - class: InlineJavascriptRequirement
```

``` bash
(env) mcrusoe@mrcdev:~/t$ cwl-runner wc3.cwl --inputfile input.txt 
/home/mcrusoe/t/env/bin/cwl-runner 1.0.20160507101510
[job wc3.cwl] /home/mcrusoe/t$ wc /home/mcrusoe/t/input.txt > /home/mcrusoe/t/input.txt.wc
Final process status is success
{
    "outputfile": {
        "size": 32, 
        "path": "/home/mcrusoe/t/input.txt.wc", 
        "checksum": "sha1$843dfe5163bcb9cc33b20d0142a10db395a71ccd", 
        "class": "File"
    }
}
```
vs using an input document
```
inputfile:
  class: File
  path: input.txt
```
``` bash
(env) mcrusoe@mrcdev:~/t$ rm input.txt.wc 
(env) mcrusoe@mrcdev:~/t$ cwl-runner wc3.cwl wc2-job1.yml 
/home/mcrusoe/t/env/bin/cwl-runner 1.0.20160507101510
[job wc3.cwl] /home/mcrusoe/t$ wc /home/mcrusoe/t/input.txt > /home/mcrusoe/t/file:///home/mcrusoe/t/input.txt.wc
Error while running job: Error collecting output for parameter 'outputfile': Did not find output file with glob pattern: '[u'input.txt.wc']'
[job wc3.cwl] completed permanentFail
Final process status is permanentFail
Workflow error, try again with --debug for more information:
  Process status is ['permanentFail']
```
