### ISSUE TITLE
Error is outputted if a cwl.output.json file is present with an outputBinding defined when called from a workflow

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/cwltool#799]
Workflow:
```
cwlVersion: v1.0
class: Workflow

inputs: []
outputs: []

steps:
  step:
    id: step
    run: test_tool.cwl
    in: []
    out: [out]
```
`test_tool.cwl`
```
cwlVersion: v1.0
class: CommandLineTool
arguments:
  - bash
  - -c
  - echo {} > cwl.output.json
inputs: []
outputs:
- id: out
  type: File?
  outputBinding:
    glob: file
```
Output:
```
$ cwltool --debug test_workflow.cwl
/Users/th10/checkouts/cwltool/venv/bin/cwltool 1.0.20180618135130
Resolved 'test_workflow.cwl' to 'file:///Users/th10/checkouts/cwltool/test_workflow.cwl'
Parsed job order from command line: {
    "id": "test_workflow.cwl"
}
[workflow ] initialized from file:///Users/th10/checkouts/cwltool/test_workflow.cwl
[workflow ] start
[workflow ] starting step step
[job step step] job input {}
[job step step] evaluated job input to {}
[step step] start
[job step] initializing from file:///Users/th10/checkouts/cwltool/test_tool.cwl as part of step step
[job step] {}
[job step] path mappings is {}
[job step] command line bindings is [
    {
        "position": [
            0,
            0
        ],
        "datum": "bash"
    },
    {
        "position": [
            0,
            1
        ],
        "datum": "-c"
    },
    {
        "position": [
            0,
            2
        ],
        "datum": "echo {} > cwl.output.json"
    }
]
[job step] /private/tmp/docker_tmp07vrpwez$ bash \
    -c \
    'echo {} > cwl.output.json'
Raw output from /private/tmp/docker_tmp07vrpwez/cwl.output.json: {}
[job step] completed success
[job step] {}
[step step] Output is missing expected field file:///Users/th10/checkouts/cwltool/test_workflow.cwl#step/out
[step step] produced output {}
[step step] completed permanentFail
[workflow ] completed permanentFail
[job step] Removing input staging directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmpcrop_l96
[job step] Removing temporary directory /private/var/folders/5p/p6z8hhy174q_ctt3pn7mx5_c000h1t/T/tmpzukuvil_
Removing intermediate output directory /private/tmp/docker_tmpvwntpp1z
{}
Final process status is permanentFail
```
