### ISSUE TITLE
Validation error when importing docker definition file as hint

### ISSUE THREAD

**Issue by samuell** [common-workflow-language/cwltool#80]
### How to reproduce:
1. Create this tool definition file, `echo.cwl`:
   
   ``` yaml
   #!/usr/bin/env cwl-runner
   
   cwlVersion: "cwl:draft-3"
   
   class: CommandLineTool
   
   hints:
     - $import: echo-docker.yml
   
   inputs:
     - id: "text"
       type: [string]
       description: |
         the text to echo
       inputBinding:
         position: 1
   
   outputs: []
   
   baseCommand:
     - echo
   ```
2. Create this docker definition file, `echo-docker.yml`:
   
   ``` yaml
   class: DockerRequirement
   dockerPull: ubuntu:16.04
   dockerFile: |
     ### Base Image
     FROM ubuntu:16.04
   ```
3. Create this job input file:
   
   ``` yaml
   text: Hello, world!
   ```
4. Execute:
   
   ``` bash
   cwl-runner --no-container echo.cwl echo_testjob.yml 
   ```
### Output received:

``````
```bash
/home/samuel/.pyenv/versions/2.7.11/bin/cwl-runner 1.0.20160427142240
Tool definition failed validation:
Validating hint `DockerRequirement`: could not validate field `id` because it is not recognized and strict is True, valid fields are: class, dockerPull, dockerLoad, dockerFile, dockerImport, dockerImageId, dockerOutputDirectory
could not validate field `name` because it is not recognized and strict is True, valid fields are: class, dockerPull, dockerLoad, dockerFile, dockerImport, dockerImageId, dockerOutputDirectory
```
``````
### Expected output:

Something else.

OS: Xubuntu 16.04 64bit
CWL Tool: 1.0.20160427142240
Python: 2.7.11
