### ISSUE TITLE
Workflow with no inputs fails validation

### ISSUE THREAD

**Issue by kghosesbg** [common-workflow-language/cwltool#806]
```
cwltool --version
1.0.20180628043715
```

When 
```
cwltool --validate generated.cwl
```

is run on the following CWL document

```
class: Workflow
cwlVersion: v1.0
id: _:1216fd9f-6ffd-42c0-bb03-7c0ad7d01017
inputs: []
outputs:
- id: '#Myout'
  outputSource: '#A/p2'
  type:
    items: File
    type: array
steps:
- id: '#A'
  in: []
  out:
  - id: '#A/p2'
  run: a.cwl
```
It complains. 

```
Tool definition failed validation:
generated.cwl:13:3: Step is missing required parameter 'p1'
```
But it is quite possible to have a workflow with no external inputs. Or is there something else wrong with this document?

Rabix Composer shows this correctly.

Thanks!
