### ISSUE TITLE
Glob with brace expression not working

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/cwltool#870]
## Expected Behavior
glob: {\*.txt,\*.png} should match all of the braced patterns.

## Actual Behavior
Nothing is returned.

## Workflow Code
```
class: CommandLineTool
cwlVersion: v1.0
baseCommand:
  - ls
inputs:
  - id: input
    type: string?
outputs:
  - id: output
    type: File[]
    outputBinding:
      glob: '{*.png,*.txt}'
requirements:
  - class: DockerRequirement
    dockerPull: 'ubuntu:16.04'
  - class: InitialWorkDirRequirement
    listing:
      - entryname: a.txt
        entry: a
      - entryname: b.png
        entry: b
stdout: b.txt
```

## Your Environment
* cwltool version: 1.0.20180721142728
