### ISSUE TITLE
passing environment variables to docker

### ISSUE THREAD

**Issue by SooLee** [common-workflow-language/cwltool#878]
Is there a way to pass an environment variable to docker while using cwltool?

I tried two ways but neither one worked.
1. runtime `--perserve-enrivonment ENVNAME` option of `cwltool`
2. Inside CWL: 
```
requirements:
  EnvVarRequirement:
    envDef:
      HELLO: $(inputs.message)
```
(as suggested by http://www.commonwl.org/user_guide/12-env/)

I want to be able to pass an environmental variable to docker using `docker run -e` option and I don't want to put that variable inside the docker image because it is related to security token.
