### ISSUE TITLE
MultipleInput: single item array is implicitly converted to single value resulting in sink mismatch

### ISSUE THREAD

**Issue by maitai** [common-workflow-language/cwltool#891]
## Expected Behavior
The `myfiles` input to the example step `concatenateFiles` (see below) is of type `File[]` as long as it contains **at least two** elements. I expect it to _still_ be of type `File[]` even when it only contains **one** element.

## Actual Behavior
When the `myfiles` input of type `File[]` only contains a single element it is _somehow_ **changed** to type `File` resulting in the error message below.
This makes it impossible to use a CommandLineTool for input file arrays of variable length because the edge case of having the array contain only a single file crashes the workflow.
The problem is not specific to the type `File[]` but affects e.g. the type `string[]` as well.

## Workflow Code
```
cwlVersion: v1.0
class: Workflow
requirements:
  - class: MultipleInputFeatureRequirement

inputs: []
outputs: []

steps:
  createFile1:
    in: []
    out:
      - myfile
    run:
      cwlVersion: v1.0
      class: CommandLineTool
      baseCommand: echo
      arguments:
        - "foo"
      inputs: []
      outputs:
        myfile: stdout

  createFile2:
    in: []
    out:
      - myfile
    run:
      cwlVersion: v1.0
      class: CommandLineTool
      baseCommand: echo
      arguments:
        - "bar"
      inputs: []
      outputs:
        myfile: stdout

  concatenateFiles:
    in:
      myfiles: 
        - createFile1/myfile
#        - createFile2/myfile
    out: []
    run:
      cwlVersion: v1.0
      class: CommandLineTool
      baseCommand: cat
      inputs:
        myfiles: File[]
      outputs: []
```

## Full Traceback
```
/usr/bin/cwltool 1.0.20180820141117
Resolved 'main.cwl' to 'file:///XXXXX/main.cwl'
Tool definition failed validation:
main.cwl:13:9: Source 'myfile' of type "File" is incompatible
main.cwl:40:7:   with sink 'myfiles' of type {"type": "array", "items": "File"}
```

## Your Environment
* cwltool version: 
`/usr/bin/cwltool 1.0.20180820141117`
* Python version:
`Python 3.7.0`
