### ISSUE TITLE
Explicitly defined empty scatter in workflow step fails validation without ScatterFeatureRequirement

### ISSUE THREAD

**Issue by AleksandrSl** [common-workflow-language/cwltool#908]
## Expected Behavior
Resolved 'example.cwl' to 'file:///home/experimental/example.cwl'
example.cwl is valid CWL.

## Actual Behavior
Resolved 'example.cwl' to 'file:///home/experimental/example.cwl'
Tool definition failed initialization:
Workflow contains scatter but ScatterFeatureRequirement not in requirements

## Workflow Code
```
class: "Workflow"
cwlVersion: "v1.0"
hints: []
inputs:
  - doc: []
    format: []
    id: "input_reads_forward"
    secondaryFiles: []
    streamable: false
    type: "File"
outputs: []
requirements: []
steps:
  - id: "first"
    in:
      - id: "input_reads_forward"
        source:
          - "input_reads_forward"
    out:
      - id: "output"
    run: "required.cwl"
    scatter: []  # this one causes problem
```

## Your Environment
* cwltool version:  1.0.20180912090223
