### ISSUE TITLE
CWL storing outputs into temp file and throwing error

### ISSUE THREAD

**Issue by ranijames** [common-workflow-language/cwltool#969]
## Expected Behavior

I have CWL script which is used to run an in house python script which takes in BAM files as input and gives out graphs. The script can be executed in parts that is in first part generate the graphs and in the second part merge the generated graphs. Currently if I run the python scripts on command line it creates the graphs and in the second run it searches in the output directory and merges the graph.
I also notice that CWL writes all output to temp strach directory and at the end writes the outputs to the defined output directory. And so it automatically never search in the working directory. And If I give a absolute path then it is throwing error message.

## Actual Behavior
The script should run and say  `- All result files already exist.` and continue with merging the graph
as the parameter given is `merge_graphs`

## The CWL workflow code
```

#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow

doc: "Workflow Components: Increment -> Spladder -> PeptidePackage"

requirements:
 - class: ScatterFeatureRequirement
  
inputs:
 spladder_gtf:
  type: File 
 spladder_bams:
  type: File[]
  secondaryFiles:
    .bai
 spladder_outDir:
  type: Directory
 spladder_confidence:
  type: int
 spladder_merge_graphs:
  type: string
 spladder_phase2:
  type: string
 spladder_alt:
  type: string
 spladder_RL:
  type: int
 spladder_validate:
  type: string


outputs:
 incre_output:
  type: File
  outputSource: increment_count/incre_output
 spladder_out1:
  type: Directory
  outputSource: spladder/spladder_out_dir1
 spladder_out2:
  type: Directory
  outputSource: spladder/spladder_out_dir2

steps:
 spladder:
  run: spladder1.cwl
  in:
   spladder_gtf: spladder_gtf
   spladder_bams: spladder_bams
   spladder_outDir: spladder_outDir
   spladder_confidence: spladder_confidence
   spladder_merge_graphs: spladder_merge_graphs
   spladder_phase2: spladder_phase2
   spladder_alt: spladder_alt
   spladder_RL: spladder_RL
   spladder_validate: spladder_validate
  out: [spladder_out_dir1, spladder_out_dir2, spladderFile]

```

## Full Traceback
```
OSError: [Errno 17] File exists: '/Alignment/spladder_out/'
Workflow error, try again with --debug for more information:
[Errno 17] File exists: /Alignment/spladder_out/'
```
The YML file
```
spladder_gtf: 
 class: File
 path: /usage_examples/gencode.v19.annotation.hs37d5_chr.spladder.gtf
spladder_outDir:/Alignment/spladder_out/
spladder_out_dir1: /spladder_out1
spladder_out_dir2: /spladder_out2
spladder_bams: [
 {class: File, path: /Alignment/C3N-02289_10_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/C3N-02289_4_5_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /cluster/work/grlab/projects/alva_temp/Alignment/C3N-02671_08_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/C3N-02671_10_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/EOC04_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/GY150806_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /JM-2_L1Aligned.sortedByCoord.out.bam},
 {class: File, path:/Alignment/Me275_L1Aligned.sortedByCoord.out.bam},
 {class: File, path:/Alignment/Me290_L1Aligned.sortedByCoord.out.bam},
 {class: File, path:/Alignment/MM170111_L1Aligned.sortedByCoord.out.bam},
 {class: File, path:/Alignment/MM909362_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/MM909432_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/RCC14_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/RCC16_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/T1015A_L1Aligned.sortedByCoord.out.bam},
 {class: File, path: /Alignment/T1185B_L1Aligned.sortedByCoord.out.bam}
]
spladder_confidence: 2
spladder_merge_graphs: merge_graphs
spladder_alt: alt_3prime
spladder_RL: 100
spladder_phase2: y
spladder_primary_alignment: y
```
## Your Environment
* cwltool version: 
Check using ``cwltool --version v1.0``
