### ISSUE TITLE
No longer able to parse json files within outputEval

### ISSUE THREAD

**Issue by jeremyadamsfisher** [common-workflow-language/cwltool#977]
## Workflow Code
```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  DockerRequirement: {dockerPull: "python"}
  InlineJavascriptRequirement: {}
baseCommand:
- python
- -c
- "import json; json.dump({'key1': 'foobar', 'key2': 2}, open('out.json', 'w'))"
inputs: []
outputs:
  output:
    type:
      type: record
      fields:
      - name: key1
        type: string
      - name: key2
        type: int
    outputBinding:
      loadContents: true
      glob: "out.json"
      outputEval: $(JSON.parse(self[0].contents))
```

## Expected Behavior
Previously, I have parsed the json output of a CommandLineTool with `JSON.parse(self[0].contents)`. The above workflow runs properly in, e.g., `v1.0.20180525185854`. It returns:

```
Javascript console output:
----------------------------------------
[log] { key1: 'foobar', key2: 2 }
----------------------------------------
[job wf.cwl] completed success
{
    "output": {
        "key2": 2,
        "key1": "foobar"
    }
}
Final process status is success
```

## Actual Behavior
Now, I get a validation error:

```
Error validating output record. the `output` field is not valid because
  * the `key1` field is not valid because
      the value is not string
  * the `key2` field is not valid because
      `[]` is not int
 in {
    "output": {
        "key1": [],
        "key2": []
    }
}
```

## Full Traceback
```
[job wf.cwl] /private/tmp/docker_tmp5xw1jlmb$ docker \
    run \
    -i \
    --volume=/private/tmp/docker_tmp5xw1jlmb:/uYEajn:rw \
    --volume=/private/var/folders/x0/0s7bygdj26db4gd20fx6t7k00000gn/T/tmpk1xyygwi:/tmp:rw \
    --workdir=/uYEajn \
    --read-only=true \
    --user=501:20 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/uYEajn \
    --cidfile=<REDACTED>/minimal_failing_example/20181115133418-855907.cid \
    python \
    python \
    -c \
    'import json; json.dump({'"'"'key1'"'"': '"'"'foobar'"'"', '"'"'key2'"'"': 2}, open('"'"'out.json'"'"', '"'"'w'"'"'))'
Running with support for javascript console in expressions (DO NOT USE IN PRODUCTION)
Javascript console output:
----------------------------------------
<REDACTED>/python3.7/site-packages/cwltool/sandboxjs.py:342: FutureWarning: Possible nested set at position 2
  r'^[[](?:log|err)[]].*$', stderr, flags=re.MULTILINE)))
[log] { key1: 'foobar', key2: 2 }
----------------------------------------
[job wf.cwl] Job error:
Error validating output record. the `output` field is not valid because
  * the `key1` field is not valid because
      the value is not string
  * the `key2` field is not valid because
      `[]` is not int
 in {
    "output": {
        "key1": [],
        "key2": []
    }
}
[job wf.cwl] completed permanentFail
{}
Final process status is permanentFail
```

## Environment
* cwltool version: 1.0.20181102182747

**Comment by tetron** [comment]
I think you might be running into this: https://github.com/common-workflow-language/common-workflow-language/issues/793

Short answer, use `|-` for yaml multi-line literals, eg:

```
      outputEval: |-
        ${
          var res = JSON.parse(self[0].contents)
          console.log(res);
          return res;
        }
```

**Comment by jeremyadamsfisher** [comment]
Unfortunately, that doesn't fix the issue. This is the case even when using a one-liner, like `outputEval: $(JSON.parse(self[0].contents))`.

**Comment by jeremyadamsfisher** [comment]
Notably, the following works:
```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  DockerRequirement: {dockerPull: "python"}
  InlineJavascriptRequirement: {}
baseCommand:
- python
- -c
- "import json; json.dump({'key1': 'foobar', 'key2': 2}, open('out.json', 'w'))"
inputs: []
outputs:
  output:
    type: string
    outputBinding:
      loadContents: true
      glob: "out.json"
      outputEval: $(JSON.parse(self[0].contents).key1)
```
This outputs:
```
[job wf.cwl] completed success
{
    "output": "foobar"
}
Final process status is success
```
It seems the issue is with mapping the javascript object to a cwl record, no?

**Comment by Zymergen-phaverty** [comment]
Maybe a JSON file created within this step is somehow different than a JSON file received as an input?  Maybe you need to use InitialWorkDirRequirement to copy the input file to the current workdir or something?  I'm tracking down a similar bit of weirdness ...

**Comment by jeremyadamsfisher** [comment]
I gave that a shot and but no luck.

`{"key1": "foobar", "key2": 2}`

```yaml
cwlVersion: v1.0
class: CommandLineTool
requirements:
  DockerRequirement: {dockerPull: "alpine"}
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing: $([inputs.myJsonFile])
baseCommand: [whoami]
inputs:
  myJsonFile:
    type: File
outputs:
  output:
    type:
      type: record
      fields:
      - name: key1
        type: string
      - name: key2
        type: int
    outputBinding:
      loadContents: true
      glob: "foo.json"
      outputEval: |-
        ${
          var res = JSON.parse(self[0].contents)
          console.log(res);
          return res;
        }
```

`cwltool minimal_failing_example.cwl --myJsonFile foo.json`

Still gives:
```
ERROR [job minimal_failing_example.cwl] Job error:
Error validating output record. the `output` field is not valid because
  * the `key1` field is not valid because
      the value is not string
  * the `key2` field is not valid because
      `[]` is not int
 in {
    "output": {
        "key1": [],
        "key2": []
    }
}
```
Thats with version 1.0.20190621234233. I just updated to 2.0.20200126090152 and get the same output.

I abandoned this approach a while ago, which is a shame because it was a nice design pattern. Would be interested to see it fixed.
